### ISSUE TITLE
Questionary To Do List

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#131]
- [x] List of platforms should be based on list of directories in `src/swell/deployment/platforms`
- [x] Set the run ahead limit to string in case the workflow is not time based. Default can be 'P4'
- [x] Ignore __pycache__ when presenting list of directories that represent workflows to choose from.
- [x] Currently the user is allowed not to choose a model but they should have to choose at least one. Maybe that means it should be changed to drop-list?
- [x] Choices for which models should be based on what is in the directory. I.e. the options geos_atmosphere and geos_ocean are presented because those directories exist.
- [x] Choices for observations should be based on what is available in `src/swell/configuration/jedi/<interface>/<model_name>/observations`.
- [x] Switch the cycle times in atmosphere and ocean to be a check list.
- [x] Add some verbosity stating the beginning and end of questions related to a certain model?
- [x] Spaces between questions?

**Comment by CRWayman** [comment]
Done!
