### ISSUE TITLE
Towards non-cycling 3DVar 

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#144]
Dan:
- [x] Split the `GenerateBClimatology` task into two: Linking and Making
- [x] Switch 3DVar suite file to only use the linking method
- [ ] (Second PR?) Allow for customization of number of processors.

Doruk:
- [X] Prepare 1 degree grid file (75 levels) for SOCA in SwellStaticData.
- [x] Interpolate 1/4 degree backgrounds from Santha to the one degree and add to R2D2.
- [x] Prepare Static B files for 1 node 1 degree
- [x] Identify 3DVar configuration that runs on minimum number of processors. Maybe 5 iterations say.

**Comment by danholdaway** [comment]
OK. So once you have the one degree states you can create the static b using 24 procs and I can add the swell_static_files_path. You can also test it by adding swell_static_files_path_user to your YAML.

**Comment by Dooruk** [comment]
I'm done with my part. I wonder if it would be useful to have a suite for convert state in Swell, even though gridgen requiring MOM restart file (chicken & egg issue).

Perhaps we could have a general suite like utilities such as conversion, gridgen, variable extraction etc. but that's down the road.
