### ISSUE TITLE
A first crack at model (coupled or uncoupled) workflow

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/swell#148]
## Following is a list of things to-do 
(spelled out by @danholdaway, additional notes from @sanAkel)

1. Clone [GEOS gcm](https://github.com/GEOS-ESM/GEOSgcm)
2. Build GCM
    - Dependencies:
       - Git, [mepo](https://github.com/GEOS-ESM/mepo)- can be accomplished by loading `GEOSenv` module on discover ⬅️ @mathomp4 please verify.
     - _Easiest_ approach: [Single Step Building of the Model](https://github.com/GEOS-ESM/GEOSgcm#single-step-building-of-the-model)
 3. Get restarts ⬅️ For now, _user_ provides a directory containing _full_ set of required restarts _valid_ for the start date of simulation; coupled includes sea ice and ocean restarts.
 4. Prepare run directory, similar to the _scratch_ directory that [gcm_run.j creates](https://github.com/GEOS-ESM/GEOSgcm_App/blob/da209421e1b17ba4a635270c325273fb7c959f79/gcm_run.j#L72).
 5. Run [GEOSgcm.x](https://github.com/GEOS-ESM/GEOSgcm_App/blob/da209421e1b17ba4a635270c325273fb7c959f79/gcm_run.j#L934-L935). Save whatever output and/or restarts that need saving.

Scope of this effort will be limited to model forecast only; nothing else, for e.g., EMIP and others that [gcm_run.j](https://github.com/GEOS-ESM/GEOSgcm_App/blob/develop/gcm_run.j) are left for later- as needed and as contributions from other users/groups arrive.

**Participants**:
@danholdaway, @sanAkel, @Dooruk, @gmao-cda

**Comment by mathomp4** [comment]
> * Git, [mepo](https://github.com/GEOS-ESM/mepo)- can be accomplished by loading `GEOSenv` module on discover ⬅️ @mathomp4 please verify.

@sanAkel Yes, although you can just load `other/mepo` to get `mepo`. But you'd probably want `git/2.38.1` and `cmake/3.23.1` on discover as well.[^1]

[^1]: I think it's time to ask NCCS to build newer versions. Those are slightly old git and cmake...

**Comment by sanAkel** [comment]
Thanks @mathomp4, I'll send an email/ticket to NCCS support.

What versions do you prefer?

**Comment by mathomp4** [comment]
@sanAkel Oh. I'll contact them. They are used to seeing it from me. Thanks though! :)

**Comment by sanAkel** [comment]
Thanks @mathomp4 Let us know when they have installed them.

**Comment by danholdaway** [comment]
@sanAkel I've completed the blank slate for a forecast suite and put in a PR here https://github.com/GEOS-ESM/swell/pull/150. Likely we'll have to add more to it as we figure out what we don't know. But there is a task there where you can start to put the scratch directory creation. It is here: https://github.com/GEOS-ESM/swell/blob/feature/forecast/src/swell/tasks/prep_geos_run_dir.py

Note that you put all the work in the `execute` method of the task. Do not add any kind of `__init__` to that class as the base class does that work. In the self construct you have access to the config and a logger. You can look at other tasks to see what they do.

**Comment by danholdaway** [comment]
@mathomp4 would you be able to add @sanAkel to the Swell team please? I think it's a requirement for pushing a branch to the swell repo.

**Comment by mathomp4** [comment]
> @mathomp4 would you be able to add @sanAkel to the Swell team please? I think it's a requirement for pushing a branch to the swell repo.

Done.

**Comment by mathomp4** [comment]
Also to @sanAkel, in talking with Dan on Teams, I realized if you need GEOS, at least for testing, it might be easiest to just get a release tarball. They are the ones with `COMPLETE` as seen here:

https://github.com/GEOS-ESM/GEOSgcm/releases/tag/v10.25.0

That has all the subrepos in it with no git stuff. So if you just need code, that might be simplest!

**Comment by sanAkel** [comment]
Thanks @mathomp4, @danholdaway.

I will have to learn a bit here and make myself a test set up. I know nothing at this moment!
Will use the tar bundle when working on `clone` part of the list.

**Comment by Dooruk** [comment]
I would like to make sure we are all on the same page in terms of model resolutions following the latest updates.

## SOCA

These are the configurations we currently have for **SOCA** (i.e., the ones **NOAA / JCSDA** provided). We can currently run Swell 3dvar (SOCA) with configurations 2 and 3, soon with all:

1. 72x35x25
2. 360x320x75 
3. 1440x1080x75

## **GEOS**

This latest [update](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/712) (712), show that **MOM6** within **GEOS** has three resolutions:

1. 72x36
2. 540x458
3. 1440x1080

So in terms of testing, **without taking any intermediate steps**, I can only use Swell/SOCA and GEOS/MOM6 with the 1440x1080 configuration. Which eventually what we are aiming for, but (for now) not feasible with the queue times and especially while we figure out the workflow where rapid computation times are required.

## QUESTIONS 

- **Main question:** How hard it is to create new resolution setups (in particular, ones matching JCSDA SOCA) using GEOS-MOM6? 
- Why do we have a 0.66 deg setup? I thought we asked for 1 deg.
- Mismatch between 72 x 35 (SOCA) vs. 72 x 26 (GEOS/MOM6). Would this be a quick fix on my end (few changes in MOM_input perhaps)?
- (I guess) Are ocean vertical levels not hard coded? Just to confirm. 

> Also to @sanAkel, in talking with Dan on Teams, I realized if you need GEOS, at least for testing, it might be easiest to just get a release tarball. They are the ones with `COMPLETE` as seen here:
> 
> https://github.com/GEOS-ESM/GEOSgcm/releases/tag/v10.25.0
> 
> That has all the subrepos in it with no git stuff. So if you just need code, that might be simplest!

- Does this tag still hold up after the latest PR (712, regarding 0.66 degrees update)? This is what I'm currently building.

**Comment by sanAkel** [comment]
@Dooruk 

> ## QUESTIONS
> * **Main question:** How hard it is to create new resolution setups (in particular, ones matching JCSDA SOCA) using GEOS-MOM6?

Not so hard. 

As you can see, we have been able to do it three times (created 3 configurations), so we can create one or a thousand more! The painful thing is to _test_ them and make sure they are _properly_ working-- That is up to _you_. We tested those three and if you want others, do as you wish ...

> * Why do we have a 0.66 deg setup? I thought we asked for 1 deg.

We picked this because aligns with other issues we have.

> * Mismatch between 72 x 35 (SOCA) vs. 72 x 26 (GEOS/MOM6). Would this be a quick fix on my end (few changes in MOM_input perhaps)?

Where is the `ocean_hgrid.nc` for your `72 x 35 (SOCA)` ? We can tag up and figure out.

> * (I guess) Are ocean vertical levels not hard coded? Just to confirm.
> 
No. They are set at _run_ time.

> > Also to @sanAkel, in talking with Dan on Teams, I realized if you need GEOS, at least for testing, it might be easiest to just get a release tarball. They are the ones with `COMPLETE` as seen here:
> > https://github.com/GEOS-ESM/GEOSgcm/releases/tag/v10.25.0
> > That has all the subrepos in it with no git stuff. So if you just need code, that might be simplest!
> 
> * Does this tag still hold up after the latest PR (712, regarding 0.66 degrees update)? This is what I'm currently building.

If you can find a more recent version `v10.25.0` (larger number ➡️ newer version) use that tarball.
