### ISSUE TITLE
sat-data-base pointing to incorrect location

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#167]
Dan,

The script:

https://github.com/GEOS-ESM/swell/blob/develop/src/swell/utilities/sat_db_utils.py

is pointing to the source code in order to exercise the satellite database capability. Nothing should ever point to the source code ... this needs to point to the installation in geos.

install/etc/gmao_satinfo.db/

Applications to handle the conventional and ozone observation databases will also be needed in swell. Notice these are also in the installation of GEOS:

install/etc/gmao_convinfo.db
and 
install/etc/gmao_ozone.db

**Comment by danholdaway** [comment]
OK, thanks.
