### ISSUE TITLE
CO2-affected radiances

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#170]
I am glad to report that I can assimilate, for example, AMSU-A on N15 (and other traditional MW radiance data) when I use it in the context for the GSI-climatological B. The increments look reasonable tough the agreement with GSI is not quite satisfactory from my perspective.

I started looking at the possible culprits: (i) TSkin sensitivity (as reported in an early issue); and now I am looking at CO2.

First I should say that the only way I can run anything using MW is by replacing yaml lines of the form:
 
Absorbers: [H2O,O3,CO2]

with simply

Absorbers: [H2O,O3]

If I have CO2, the crashes for me ... perhaps I don't have the latest UFO - to be checked. 

But the above lead me to look around a little more closely, and in SWELL, I don't CO2 being passed in the background files. Therefore, even for those who are successful in using all there absorbers above, the fact is that it seems that GSI is not using CO2-affected radiances the same way as GMAO GSI is. 

I hope this issue can help us have a discussion about this and address any missing pieces.

**Comment by danholdaway** [comment]
For CO2 it gets set to a constant. You can see that [here](https://github.com/JCSDA-internal/fv3-jedi/blob/10d0b4e76a09342bc9ed0ed492e16735dd54358e/src/fv3jedi/VariableChange/Model2GeoVaLs/fv3jedi_vc_model2geovals_mod.f90#L876). At some point I was told that this is what GSI was doing, but it's possible that was an NCEP centric view. Are you saying that the GEOS model provides an evolving background field for CO2 when you run GSI? 

The crash might be because if you set the absorbers to CO2 it automatically adds that to the Jacobean and tries to get C02 from the increment of fv3-jedi, and it never has that field. We might need to add a `linear obs operator`. There's an example of that [here](https://github.com/JCSDA-internal/ufo/blob/f2135da8a87bfb40251c291430e826b9f745f59c/test/testinput/unit_tests/operators/smap_crtm.yaml#L12). You could try setting the absorbers to be `[H2O,O3,CO2]` in the `obs operator` config and be `[H2O,O3]` in the `linear obs operator` config.

**Comment by danholdaway** [comment]
Let me know if the above works and we can add it to the YAMLs in Swell.

**Comment by rtodling** [comment]
Dan: thanks for the input - but I am using exactly the yaml that's in swell - I am not fussing w/ it. The yaml for AMSUA-n15 does have the absorber in two locations:

     obs operator:
        name: CRTM
        Absorbers: [H2O,O3,CO2]
        linear obs operator:
          Absorbers: [H2O,O3,CO2]

So - I have it in the linear operator ... but could the error be associated w/ the same thing we were looking back on Friday where GeoVals did not have a reference to CO2 - but that would be odd since I assume the yamls on develop work in your nightly tests.

As for the actual configuration:
1) NCEP uses the constant value of CO2 - fitting the settings that are presently in the swell yawls
2) GMAO uses CO2 as provided in the  background  file  - unfortunately, your x0044 files does not carry that - an oversight just as the mix up between TA and TS - I do however have CO2 included in these jedi-required-background files coming out of recent history. So we should at some point update the files you have been pointing to.

In any case, the code needs an option that sets how the absorbers are handled - some might/will come from the background. Note that - though not yet - this would be an option required to be able to pass GOCART aerosols to CRTM and have aerosol affected radiances (a capability that GSI has - but it does not trigger by default).

**Comment by rtodling** [comment]
Just to confirm what I said about GeoVals ... this is the error I get:

GeoVaLs (AD) field mole_fraction_of_carbon_dioxide_in_air has no known link to fields in model state
GeoVaLs (AD) field mole_fraction_of_carbon_dioxide_in_air has no known link to fields in model state
Abort(1) on node 18 (rank 18 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 18
GeoVaLs (AD) field mole_fraction_of_carbon_dioxide_in_air has no known link to fields in model state

**Comment by danholdaway** [comment]
Can you try changing your YAML to:

``` YAML
obs operator:
  name: CRTM
  Absorbers: [H2O,O3,CO2]
linear obs operator:
  Absorbers: [H2O,O3]
```

This will hopefully prevent the error you see in the GeoVaLs.

**Comment by danholdaway** [comment]
We'll have to make a fix in the Model2GeoVaLs nonlinear code to allow CO2 to come from the background instead of a constant value.

**Comment by rtodling** [comment]
Sorry for the slow reply; had a meeting that just ended. Yes, that does work - that is, removing CO2 from the linear model.

Thank you.

**Comment by danholdaway** [comment]
OK great. I'll make the change in the swell yamls at some point. I think that is what we want for the meteorology DA. Maybe someone like Brad will eventually want increments of CO2 as well but that would be longer term and in a different YAML that includes CO2 in the increment.

**Comment by rtodling** [comment]
Well - we need more than changes in the yamls (swell) - we need for CRTM to see the CO2 from GEOS's background. There will be no increments on CO2, but the radiance need to be affected by GEOS CO2 .. this is a CRTM interface change; wherever that call is made in UFO -

Just to make sure. I am not saying the changes in yaml are not needed - there are. We don't need the linear model to see CO2.  But we do the observer to have access to the background CO2 as an alternative option.

**Comment by danholdaway** [comment]
The changes aren't in ufo, they would be in fv3-jedi. I'll make the change and issue a PR for you to test with the proper backgrounds.

**Comment by danholdaway** [comment]
I have created a PR in fv3-jedi to address this issue and allow reading of CO2 from the background https://github.com/JCSDA-internal/fv3-jedi/pull/851

**Comment by rtodling** [comment]
I will add a comment here - I hope someone in the obs group working directly on radiance can comment on this. 

You have shown me - and indeed I was able to eventually corroborate - that the count for, for example, AMSUA N15 observations in JEDI are close if not identical to those from GSI. But the puzzling matter to me is: if JEDI was not accounting for the CO2 effect as GSI is, how could the counts be the same? I know for a fact that one of the consequences of changing the CO2 prescription is the count of radiance observations.

At the same time, I had shown you what I have for Jo and Jo/n for OmA and OmB and that they differ quite non-trivially  from those of GSI. Just to keep the record I am adding a little figure here.


<img width="741" alt="jo_amsua" src="https://user-images.githubusercontent.com/14125601/232792213-55feb71f-265a-44d7-81bf-412e52c1fae4.png">

Obviously the diff in Jo(OmA) can still be my doing - for not properly treating something related to B correctly - and I have evidence of that being the case as of last night on 4/18/23. But the OmB is not quite my doing - it comes from UFO. It's possible that the differences I see are associated with the CO2 treatment. Once address the issue I have w/ the control vector, I will merge what I have w/ the changes from Dan and give it another try.

But the puzzle of the count remains ...

**Comment by gmao-yzhu** [comment]
@rtodling  please be aware that identical results were achieved in the UFO framework using testing geoval files from GSI. If you use swell system and generate geoval directly from swell, it is not expected to get the same results as gsi.  the obs group can take a closer look at what you said above.

**Comment by rtodling** [comment]
But to get consistency you would have to have CO2 in geoVals ... which we do not. I don't understand how the hofx from JEDI would match that of GSI when CRTM is using a differ CO2 prescription.

**Comment by gmao-yzhu** [comment]
I looked our testing file we used in our consistency tests, we had "mole_fraction_of_carbon_dioxide_in_air" in our testing geoval file, it was not constant, and this variable was used in the radiance simulation. So I don't see a problem with co2. Did you save co2 geoval values in "mole_fraction_of_carbon_dioxide_in_air" in swell?

**Comment by rtodling** [comment]
Ah ... my mistake. When I looked at setuprad - looking for the corresponding quantity I missed that it's actually written out as on of the CRMT absorbers which in the case of CO2 is set to a varying field. Very good. 

Thank you.

**Comment by danholdaway** [comment]
Just to add to this...and what Yanqui was saying, one thing we have yet to do properly is verify that the actual GeoVaLs coming from fv3-jedi are correct. This is something on the radar of ourselves and also Cory et al at NCEP. We need to verify that the spatial interpolation is doing the correct thing and more importantly that the variable transforms for the surface quantities are correct. In the past we've seen weird things like snow over ice in one system and not the other. Once we wrap up the conventional data we'll turn our attention to radiance GeoVaLs and check on all these variable transforms.

**Comment by rtodling** [comment]
> Just to add to this...and what Yanqui was saying, one thing we have yet to do properly is verify that the actual GeoVaLs coming from fv3-jedi are correct. This is something on the radar of ourselves and also Cory et al at NCEP. We need to verify that the spatial interpolation is doing the correct thing and more importantly that the variable transforms for the surface quantities are correct. In the past we've seen weird things like snow over ice in one system and not the other. Once we wrap up the conventional data we'll turn our attention to radiance GeoVaLs and check on all these variable transforms.

Sounds good Dan.
