### ISSUE TITLE
x0048 End Game

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#224]
## PRs

fv3-jedi
- https://github.com/JCSDA-internal/fv3-jedi/pull/1019

ioda converters

- https://github.com/JCSDA-internal/ioda-converters/pull/1363
- https://github.com/JCSDA-internal/ioda-converters/pull/1362

ufo
- https://github.com/JCSDA-internal/ufo/pull/3026
- https://github.com/JCSDA-internal/ufo/pull/3023
- https://github.com/JCSDA-internal/ufo/pull/3016
- https://github.com/JCSDA-internal/ufo/pull/3013
- https://github.com/JCSDA-internal/ufo/pull/3050

swell
- https://github.com/GEOS-ESM/swell/pull/226
- https://github.com/GEOS-ESM/swell/pull/229
- https://github.com/GEOS-ESM/swell/pull/231
- https://github.com/GEOS-ESM/swell/pull/244

## Sondes
- [x] Create YAML for non-Pibal sondes (Wei & Akira)
    - [x] Winds
    - [x] Temperatures
    - [x] Surface pressure
    - [x] Humidity
- [x] Create YAML for PIbals (Jianjun)

## Winds

- [x] Add code to perform wind scaling in vertical interpolation

## GPS
- [x] Waiting on JCSDA

**Comment by danholdaway** [comment]
@asewnath @gmao-wgu @gmao-jjin3 Pibal matches with UFO branch `feature/subtract_surface_coodindate`

## windEastward
![corscat_hofxdiff_vs_gsi](https://github.com/GEOS-ESM/swell/assets/27729500/ce192d5c-d968-4289-8f8b-fb6d851d0197)
![corscat_eferr_vs_finaler](https://github.com/GEOS-ESM/swell/assets/27729500/533d9739-8e6e-44ca-9b69-0511ce2885b0)
![density_qc_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/27729500/e06dae8d-f92d-4167-8bd2-2f2b19e6a9e4)

## windNorthward
![corscat_hofxdiff_vs_gsi](https://github.com/GEOS-ESM/swell/assets/27729500/ada84fd1-d57a-4ecc-95d1-2f7fe9eadaa7)
![corscat_eferr_vs_finaler](https://github.com/GEOS-ESM/swell/assets/27729500/dc76b49b-3772-4302-848d-29aba842818e)
![density_qc_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/27729500/9c0a0bdb-f0dc-4ac8-ba1e-5bd72d20f043)

**Comment by rgelaro** [comment]
Excellent!
________________________________
From: Dan Holdaway ***@***.***>
Sent: Monday, September 18, 2023 11:12 AM
To: GEOS-ESM/swell ***@***.***>
Cc: Gelaro, Ronald (GSFC-6101) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/swell] x0048 End Game (Issue #224)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.




@asewnath<https://github.com/asewnath> @gmao-wgu<https://github.com/gmao-wgu> @gmao-jjin3<https://github.com/gmao-jjin3> Pibal matches with UFO branch feature/subtract_surface_coodindate

windEastward

[corscat_hofxdiff_vs_gsi]<https://user-images.githubusercontent.com/27729500/268688587-ce192d5c-d968-4289-8f8b-fb6d851d0197.png>
[corscat_eferr_vs_finaler]<https://user-images.githubusercontent.com/27729500/268688617-533d9739-8e6e-44ca-9b69-0511ce2885b0.png>
[density_qc_omb_vs_gsiomb]<https://user-images.githubusercontent.com/27729500/268689217-e06dae8d-f92d-4167-8bd2-2f2b19e6a9e4.png>

windNorthward

[corscat_hofxdiff_vs_gsi]<https://user-images.githubusercontent.com/27729500/268688760-ada84fd1-d57a-4ecc-95d1-2f7fe9eadaa7.png>
[corscat_eferr_vs_finaler]<https://user-images.githubusercontent.com/27729500/268689099-dc76b49b-3772-4302-848d-29aba842818e.png>
[density_qc_omb_vs_gsiomb]<https://user-images.githubusercontent.com/27729500/268688854-9c0a0bdb-f0dc-4ac8-ba1e-5bd72d20f043.png>
