### ISSUE TITLE
Use Geometric height for surface conventional data

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#250]
The YAMLs for scatwind, sfc and sfcship are using geopotential height. But this should be geometric height. This will require some changes on the fv3-jedi side. I believe Emily @ EMC was going to look at this.

https://github.com/GEOS-ESM/GEOSana_GridComp/blob/develop/GEOSaana_GridComp/GSI_GridComp/setupw.f90#L661

**Comment by gmao-jjin3** [comment]
If I remember correctly, you said there was no difference to use geometric or geopotential height. Maybe we add a note and don't need worry about it.

**Comment by gmao-jjin3** [comment]
It turns out that all sfcship wind and scatwind data are located below the 1st model level. 

```
For sfcwind:
In /discover/nobackup/jjin3/SwellExperiments/swell-ufo_testing/run/20211212T000000Z/geos_atmosphere/sfcship.20211211T210000Z.nc4
For non-missing  ObsValue/windEastward :
Difference (height-stationElevation) - geometric_height at level 1
 -- range: [ -57.87725 , -39.171406 ]
Difference (height-stationElevation) - geopotential_height at level 1
 -- range: [ -57.722137 , -39.139893 ]
 
For scatwind:
/discover/nobackup/jjin3/SwellExperiments/swell-ufo_testing/run/20211212T000000Z/geos_atmosphere/scatwind.20211211T210000Z.nc4
Difference  MetaData/height - geometric_height at level 1
 -- range: [ -57.63452 , -47.10039 ]
Difference  MetaData/height - geopotential_height at level 1
 -- range: [ -57.467873 , -47.16102 ]

```
As to sfc data, there is no wind data are used. As a result, Hofx values are derived from values at the lowest model level and there is no interpolation from values at model levels above it.  That explains why there is no difference between results made with geometric and geopotential vertical coordinates.

**Comment by gmao-jjin3** [comment]
In the geoval files, surface geometric heights are identical to surface geopotential heights. However, 3-D geometric heights (at model levels) are indeed different from 3-D geopotential heights.  Here are some differences between geometric and geopotential heights at surface and at model levels in 
/discover/nobackup/jjin3/SwellExperiments/swell-ufo_testing/run/20211212T000000Z/geos_atmosphere/scatwind_geovals.20211211T210000Z.nc4: 
```
Difference  surface_geometric_height - surface_geopotential_height :
 -- range: [ 0.0 , 0.0 ]

Size of (geometric_height - geopotential_height) : (8413, 72)
Difference  geometric_height - geopotential_height :
 -- range: [ -8.245605 , 1133.6328 ]

geometric_height at level 1
 -- range: [ 57.10039 , 67.63452 ]

geopotential_height at level 1
 -- range: [ 57.16102 , 67.46787 ]
```

**Comment by danholdaway** [comment]
@gmao-jjin3 thanks for doing that investigation. That explains why it doesn't make a difference. It might be that once we switch to more model levels in GEOS we can't assume that all the observations are below the lowest model level. This might explain why emc have found the need to have geometric height instead of geopotential height, while we haven't seen that. So we should probably go ahead with implementing geometric height in fv3-jedi and changing these YAMLS to use that variable instead but perhaps it is not urgent and we let EMC do that work?

**Comment by gmao-jjin3** [comment]
I don't think it is urgent. All satellite surface winds are made by referencing to 10-meter wind. Ship wind can be made at higher altitudes. But, most of them are below 20 meters. See:

```
/discover/nobackup/jjin3/SwellExperiments/swell-ufo_testing/run/20211212T000000Z/geos_atmosphere/scatwind.20211211T210000Z.nc4
height-stationElevation range = [ 10.0 , 10.0 ]

/discover/nobackup/jjin3/SwellExperiments/swell-ufo_testing/run/20211212T000000Z/geos_atmosphere/sfcship.20211211T210000Z.nc4
height-stationElevation range = [ 0.0 , 20.0 ]

``` 
I don't know the lowest level height in Bill Putman's new vertical grids, but I doubt it is changed from about 50m to below 20m.  We may need ask him about it, but I think we can wait for EMC.

**Comment by danholdaway** [comment]
Now tracked in fv3-jedi https://github.com/JCSDA-internal/fv3-jedi/issues/1074
