### ISSUE TITLE
Topography check (filter) does not work for AMSUA

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#272]
Over and over again, with multiple versions of UFO/JEDI/etc I have tried putting this filer back in what I use, but it remains an issue for me. 

<img width="1201" alt="Untitled" src="https://github.com/GEOS-ESM/swell/assets/14125601/8ee915fb-bde4-4775-b4cb-489355b0bc79">

The fig shows diff in yaml of AMSUA-N15 from swell (left) and what I end up using (right).

the error I get  when using the swell version is the following:

Exception: ObsFunction/ObsErrorFactorTopoRad does not exist in FilterActionFactory
Exception: oops::Variational<FV3JEDI, UFO and IODA observations> terminating...

I've been trying to stick to what's in SWELL, but I have had to do some massaging since things refuse to work in an analysis context. This is one of the recurring problems.

**Comment by danholdaway** [comment]
OK. Thanks Ricardo. We'll take a look.

**Comment by gmao-jjin3** [comment]
@rtodling  Can you change "Blacklist" to "Perform Action" for that filter and give another try?
Here is an example:
/discover/nobackup/jjin3/opt/src/swell/singleobs/src/swell/configuration/jedi/interfaces/geos_atmosphere/observations/amsua_n15.yaml.jj 

I couldn't reproduce the error and don't know why at the moment.

**Comment by rtodling** [comment]
I think can be closed now.
