### ISSUE TITLE
(SE) `defer_to_model` considers one model at a time

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#280]
`defer_to_model` works as intended when `all` or a single model (`geos_ocean` or `geos_atmosphere`) options are used.

When multiple model names are entered manually, as shown below, only the first model entry is considered while updating the experiment config.

<img width="241" alt="Screenshot 2023-12-05 at 1 38 06 PM" src="https://github.com/GEOS-ESM/swell/assets/38666458/f65de432-3a97-4a81-8a17-e1354b683536">

**Comment by Dooruk** [comment]
This is an old issue but we need to test if this is still the case at some point.

**Comment by mranst** [comment]
It seems like this is not currently the case. I tested `localensembleda` by adding `geos_ocean` under `path_to ensemble` in task_questions.yaml, like in the example. I also had to add `geos_ocean` to `model_components`, otherwise `geos-ocean`-related entries will be ignored, but `path_to_ensemble` was registered in the experiment config, though it just has the value “defer_to_model” since there isn’t a corresponding value in the `geos-ocean` yaml.

**Comment by Dooruk** [comment]
> It seems like this is not currently the case.

Hmm, I still see this problem. I am doing exactly what you said and I get `path_to_ensemble` only for the `geos_atmosphere`.  I changed `task_questions.yaml` and activated `geos_ocean` in  `model_components`.

Another issue I'm seeing actually is that I can't get `geos_ocean` to be added in `experiment.yaml` unless I use it in the `override.yaml`. In other words, `locaensembleda-tier1.yaml` does not use `geos_ocean` even if I add it in the `model_components`.

**Comment by mranst** [comment]
Huh, that's very confusing. I may be misunderstanding the issue, but for me just changing those two lines results in it being added to experiment.yaml

https://github.com/mranst/swell/blob/4b52acdf2eb950e1a429392246a45da30436f74f/src/swell/tasks/task_questions.yaml#L784-L789

https://github.com/mranst/swell/blob/4b52acdf2eb950e1a429392246a45da30436f74f/src/swell/test/suite_tests/localensembleda-tier1.yaml#L3

https://github.com/mranst/swell/blob/4b52acdf2eb950e1a429392246a45da30436f74f/experiment.yaml#L31-L91

**Comment by Dooruk** [comment]
Huh, the only difference I have is the order in `model_components`: `['geos_atmosphere', 'geos_ocean']`. Could you try that way while I try your way?

**Comment by mranst** [comment]
I had that thought earlier as well, I just tried it again and the result is the same other than the order of models in the `experiment.yaml`. Are you using an `override.yaml`?

**Comment by Dooruk** [comment]
Alright, I tested the same changes with a fresh clone and that worked. Thanks @mranst! 

I assume the fix may have happened during Dan's latest refactoring of the suite creation.
