### ISSUE TITLE
Add new Swell CLI option

### ISSUE THREAD

**Issue by CEgerer93** [GEOS-ESM/swell#288]
A potential workflow to support computation of ensemble observers in the `localensembleda` suite includes the definition of a new variable `ensemble_hofx_strategy`; this variable will allow toggling between serial and parallel run patterns. It would be helpful for Swell to know how to distribute subsets of H(x) computations between allocated nodes when `ensemble_hox_strategy = parallel`. One thought is to include a new command line option to `swell task`, such as the following:

https://github.com/GEOS-ESM/swell/blob/1af9b232063f7c33648dbcf1b67b55d134f058e6/src/swell/suites/localensembleda/flow.cylc#L163
where `-e {{packet}}` is a new option.

I have an idea where this could be done, but I worry I could be breaking some functionality. I do realize this may be a little premature as an issue, especially given the holding pattern Swell is currently in. Nonetheless, I'm curious what insight might be gained.

**Comment by Dooruk** [comment]
Thanks @CEgerer93 for mentioning this issue and suggesting a solution. Tagging @rtodling as he brought up this issue with me before. 

I have a question in regards to hofx output and ensemble numbers. After one outer loop, hofx name convention would be hofx1_0, hofx1_1, hofx1_2 and so forth. I'm wondering how this numbering would occur if there are parallel runs? Say we submit it in batches of size 5, would ensemble member 6 still be named hofx1_5 or would try to override hofx1_0? 

Also, how many ensemble members are you considering?

**Comment by CEgerer93** [comment]
I would hope to set things up so, in the case you describe, member 6 would be mapped to hofx1_5 as usual. The need for an additional option to `swell task` would, in effect, ensure member observers handled by a separate batch job don't interfere with each other.

With each task knowing the total number of members and packets, it would be trivial to assign the suffix. Maybe there's more to this than I think; I will need a refresher on the inner vs. outer loop prescription to make sure this is feasible.

For the `localensembleda` suite I put together, I was considering only 10 members (those referenced by the fv3-jedi ctests).

**Comment by Dooruk** [comment]
@CEgerer93 is very close to implementing the feature of submitting an ensemblehofx that can submit multiple Cylc compute tasks via multiple packets. We are just not crystal clear on the reason not using ensemble hofx tasks within FV3-JEDI.

 @rtodling, We could adjust the walltime request which I don't think is the issue. Perhaps the main concern here is requiring too many nodes at once even if we submit the JEDI enshofx executable for high resolution setups and we are essentially trying to distribute that load within swell? 

@danholdaway maybe you have an insight here?
