### ISSUE TITLE
Split GSI's mksi into its own repo

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#289]
To facilitate the transition to JEDI, it would be good to have mksi sit its own repo - but be placed in the same GSI_GridComp location as it stands when GEOSadas is built. 

Added Akira here so she can update swell once the change has been made.

**Comment by mathomp4** [comment]
I have two PRs and a new repo in re this. All work in progress though I can say it builds:

- https://github.com/GEOS-ESM/GEOSana_GridComp/pull/157
- https://github.com/GEOS-ESM/GEOSadas/pull/267
- https://github.com/GEOS-ESM/GEOS_mksi

**Comment by rtodling** [comment]
Can someone please try working on this in SWELL? Notice that soon I tag this and it will be important that swell pulls a tag and not develop.

**Comment by Dooruk** [comment]
> Can someone please try working on this in SWELL? Notice that soon I tag this and it will be important that swell pulls a tag and not develop.

Sure, I'm not sure what needs to be done. Perhaps @asewnath is more familiar with it? 

Is it practically cloning a repo, as is done here?:

https://github.com/GEOS-ESM/swell/blob/develop/src/swell/tasks/clone_geos_ana.py

**Comment by rtodling** [comment]
Doruk: I am trying to remember where I saw this - but somewhere in swell - perhaps when an experiment is created, it pulls the GEOSana_GridComp to tap on mksi which lives in that repo inside the GSI_GridComp. That is, swell is pulling a lot of code just to get to a directory that lives deep inside the GEOSana_GridComp repo.  

The idea here is to replace the pulling of GEOSana_GridComp w/ simple GEOS_mksi - which is truly the only part the swell machinery needs.

For example, the HOFX task looks like this (directory after task is created):

configuration
GEOSana_GridComp
jedi_bundle
stage
swell-hofx-suite

If you make the change I am requesting here, the above should like like this:

configuration
GEOS_mksi    ------>>>> this will be a much trimmed version of things
jedi_bundle
stage
swell-hofx-suite

**Comment by rtodling** [comment]
BTW: I think this is where the change needs to take place:

swell/tasks/clone_geos_ana.py

this entire script should be renamed to clone_geos_mksi.py and inside, any refs to geosana_gridcomp should change accordingly. I can try to make the change and put it in a PR if you want me to.

**Comment by asewnath** [comment]
@rtodling @Dooruk I can make these changes and will tag you in the PR when it's ready (assuming nobody else is working on it yet)

**Comment by Dooruk** [comment]
> @rtodling @Dooruk I can make these changes and will tag you in the PR when it's ready (assuming nobody else is working on it yet)

Thanks @asewnath , no I haven't started working on it.

**Comment by rtodling** [comment]
> @rtodling @Dooruk I can make these changes and will tag you in the PR when it's ready (assuming nobody else is working on it yet)

Thanks Akira - that would be nice. Pls tag me in the PR so I can learn ... thank you!
