### ISSUE TITLE
missing observations require modifying experiment.yaml

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#295]
[This previous pull request ](https://github.com/GEOS-ESM/swell/pull/286)updates executable configs inside the model directories but does not modify the `experiment.yaml`. So when there are additional tasks looping over observations, they fail when there is an observation input with 0 locations. This is what's happening with `SaveObsDiags`.

We didn't catch this with Eva because I have the following section: 

https://github.com/GEOS-ESM/swell/blob/6037ab6c230a868209c292b0e02e7590e7932af5/src/swell/tasks/eva_observations.py#L110-L113

So I need to take the empty observation sources out of the `experiment.yaml` once we identify it.

@asewnath

**Comment by asewnath** [comment]
Modifying the experiment.yaml directly is a good idea. It would be great for downstream tasks to point to this updated experiment config instead.

I think moving forward we need to make sure our review system can catch things like this. Perhaps running the tier tests locally on discover first to make sure other suites like the one you use don't break before the merge.

**Comment by asewnath** [comment]
@Dooruk was this fixed? It looks like the tier1 test is working now, wasn't SaveObsDiag the thing that was breaking it before?

**Comment by Dooruk** [comment]
No, I just took `sst_ostia` out from the ocean observations list as a quick fix but this still needs to be addressed.
