### ISSUE TITLE
Bump GEOS version to 1.5.1

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#300]
It's time for us to update develop `GEOS` version, which is quite old at this point. This way we can also create a Tier 2 test.

We have to use the `MOM_override` in this https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/65 until we update to a version that encompasses that PR.

According to @zhaobin74, CICE6 is ready for the high-res setup, sounds like there is an issue with the ocean heating that impacts the sea-ice growth, however. @sanAkel or @zhaobin74 could you please briefly clarify if this is a particular resolution issue, or CICE4 vs. CICE6 issue, or overall `GEOSgcm` issue? That wasn't clear to me during yesterday's meeting.

**Comment by zhaobin74** [comment]
I can only speak of C90-0.66 deg coupled setup with the latest CICE6. There appears a polar cool down in the v11.5.1 which resulted in accumulation of thicker ice in the Arctic. The cooling happened abruptly during the first 2 years and then leveled off. In the Arctic, increasing ice volume is associated with lack of cloud forcing during the winter season.    

I don't know whether the above applies to c180-1440x1080 config. I don't have such a run.

**Comment by sanAkel** [comment]
> I can only speak of C90-0.66 deg coupled setup with the latest CICE6. There appears a polar cool down in the v11.5.1 which resulted in accumulation of thicker ice in the Arctic. The cooling happened abruptly during the first 2 years and then leveled off. In the Arctic, increasing ice volume is associated with lack of cloud forcing during the winter season.    
> 
> 
> 
> I don't know whether the above applies to c180-1440x1080 config. I don't have such a run. 

@Dooruk Please just update to [v11.5.1](https://github.com/GEOS-ESM/GEOSgcm/releases/tag/v11.5.1) that's that matters for now.

**Comment by Dooruk** [comment]
> I can only speak of C90-0.66 deg coupled setup with the latest CICE6. There appears a polar cool down in the v11.5.1 which resulted in accumulation of thicker ice in the Arctic. The cooling happened abruptly during the first 2 years and then leveled off. In the Arctic, increasing ice volume is associated with lack of cloud forcing during the winter season.
> 
> I don't know whether the above applies to c180-1440x1080 config. I don't have such a run.

Thanks Bin, I will focus on the high-res for now with CICE4 and CICE6 setups and see if we see a similar issue.

**Comment by sanAkel** [comment]
> Thanks Bin, I will focus on the high-res for now with CICE4 and CICE6 setups and see if we see a similar issue.

This is what I'm hoping for:

1. @zhaobin74 continues to iron out CICE6 issues (`appears a polar cool down in the v11.5.1 which resulted in accumulation of thicker ice in the Arctic.`; @zhaobin74 also see a note from me in teams chat about it) at med res.
2. Get high-res configuration (with CICE4) to be better behaved **without** abruptly warming up ➡️ actively working on it.
3. Once above 2 is ✅ then @zhaobin74 and I can start working towards scientifically credible CICE6 for high-res.

@Dooruk I'll close this issue for you since you have all the info. and questions have been answered. If this is `False`, reopen. 🙏
