### ISSUE TITLE
3DVar Fails: Surface wind scaling pressure 

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#304]
The following:

hofx scaling field: SurfaceWindScalingPressure
hofx scaling field group: DerivedVariables

in the nonlinear and linear operators of most conventional obs causes 3dvar to fails.

Likely this needs a geoval that is improperly defined. Or the linear model has something incorrectly set.

**Comment by gmao-jjin3** [comment]
@rtodling I'll take another look at it.

**Comment by gmao-jjin3** [comment]
@rtodling  It is bit strange that there is no atmospheric component in my 3dvar testing suites even after I checked out the swell develop branch and rebuilt it.  Do you have a newer branch than the develop?  The test of sonde data is fine in my swell-hofx testing suite.

**Comment by gmao-jjin3** [comment]
Oops.  Found you new PR  https://github.com/GEOS-ESM/swell/pull/302

**Comment by rtodling** [comment]
I think I found the problem w/ this. The issue is in the "linear obs operator" of sondes.yaml. sfcship.yaml , sfc.yaml that's using the scaling when that's not applicable there. The other obs systems using this scaling -  don't have the entry in the linear operator, only in the non-linear op.

**Comment by gmao-jjin3** [comment]
@rtodling This issue is addressed by Fabio's PR https://github.com/JCSDA-internal/ufo/pull/3299.

**Comment by rtodling** [comment]
@gmao-jjin3 : do you want to add a PR to SWELL with the fixes associated w/ the code changes and fixed in UFO? Or should I do that?

**Comment by gmao-jjin3** [comment]
@rtodling I certainly can do that. But, did you modify "hofx scaling" in other configurations? I didn't track changes in these files. 
aircraft.yaml
pibal.yaml
satwind.yaml
scatwind.yaml
sfcship.yaml
sfc.yaml

"linear obs operator" is needed all of them and the sondes.yaml, isn't it?

**Comment by gmao-jjin3** [comment]
@rtodling  I see many these "hofx scaling" were commented when swell-3dvar_atmos was added.  I am going to un-comment them.
