### ISSUE TITLE
3DVar Fails for OMPSNM_NPP

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#305]
The following background check causes 3dvar to fail - produce negative Jo's.

# Gross check
- filter: Background Check
  filter variables:
  - name: ozoneTotal
  threshold: 5.0
  action:
    name: reject

**Comment by rtodling** [comment]
Just for the record ... this is the difference of increments between GSI(top) and JEDI(bot) for an all-ops assimilation case ... there is some disagreement in the increments that could be associated w/ the issue here - and the corresponding one for OMI #306 ...
<img width="574" alt="Untitled" src="https://github.com/GEOS-ESM/swell/assets/14125601/070310f2-d60d-4af0-b5bc-8c55ae2e8d8b">

**Comment by rtodling** [comment]
These are the discrepancies in obs counts between GSI and JEDI:
**GSI**
ozone                          8803    1.3387997847213075E+04       1.521
level ozone                   27570    5.5483810022753874E+04       2.012
ozone                          8803    1.3387997847213075E+04       1.521
level ozone                   27570    5.5483810022753874E+04       2.012
ozone                          8803    6.9459464775576898E+03       0.789
level ozone                   27570    1.5123488073171970E+04       0.549
**JEDI**
CostJo   : Nonlinear Jo(OMI AURA) = 1865.7, nobs = 2496, Jo/n = 0.747476, err = 6
CostJo   : Nonlinear Jo(OMI AURA) = 1834.52, nobs = 2496, Jo/n = 0.734984, err = 6
CostJo   : Nonlinear Jo(OMPSNM NPP) = 3007.28, nobs = 6280, Jo/n = 0.478867, err = 6
CostJo   : Nonlinear Jo(OMPSNM NPP) = 2985.36, nobs = 6280, Jo/n = 0.475376, err = 6

**Comment by karpob** [comment]
It's been a while (almost 2 years) since I did this. I've asked at least twice before for a setup I could run to debug. Does it exist yet, or is this just so you all don't forget? I've also been out of the JEDI hive mind for a while, so I'm probably fairly useless apart from debugging. Back when I was doing this, I recall something about "order" and "defer to post" I think at one point I had: 
```
filter variables:
   name: ozoneTotal
  threshold: 5.0
  action:
  name: reject
 defer to post: true
```
but took it out as it didn't make any difference when doing the HofX tests.  If someone can point me to what I can checkout and run, I'm happy to look at this.

**Comment by karpob** [comment]
@gmao-jjin3 You might want to try the "new" ColumnRetrieval operator, if you haven't already. Kris and I talked about this at one point, but one caveat ignore the comment in the following example and use this number for the "constant"
0.0022413969545014138 (probably going overboard with the number of digits there).
https://github.com/JCSDA-internal/ufo/blob/develop/test/testinput/unit_tests/operators/ompsnp_npp_columnop.yaml

**Comment by gmao-jjin3** [comment]
> @gmao-jjin3 You might want to try the "new" ColumnRetrieval operator, if you haven't already. Kris and I talked about this at one point, but one caveat ignore the comment in the following example and use this number for the "constant" 0.0022413969545014138 (probably going overboard with the number of digits there). https://github.com/JCSDA-internal/ufo/blob/develop/test/testinput/unit_tests/operators/ompsnp_npp_columnop.yaml

Thanks @karpob . This operator needs some variables in IODA data made directly from data provider's NetCDF/HDF files. Our IODA files are made from GSI output at the moment.  Anyway, this issue is solved by fixing a bug in JEDI/UFO.

**Comment by karpob** [comment]
@gmao-jjin3 Good glad it's a relatively simple fix. Out of curiosity I took a look at ColumnRetrieval. I think it may have a similar problem for us in the future. It looks like the code relies on the averaging kernel associated with the ob to check for missing values, not the values themselves. If it's a non-averaging kernel ob, it will set the averaging kernel to 1 and happily go on it's way.
