### ISSUE TITLE
Need to unwire date in eva file handling the increment 

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#311]
Presently, the date of the increment file that EVA operates on to make plots for the increment is wired. This needs to be generalized. 

Notice the different between 3dvar_atmos  and 3dfgat_atmos: the first handles an increment at the middle of the var window; the second handles the increment at the start of the window. 

I believe handling 3dfgat will require a (minor) change in the workflow for 3dfgat: either a date change or the calculation of the increment in the middle of the window (offline; that is not in the var).

Just for reference these are the lines that need  generalization:

3dVar - https://github.com/GEOS-ESM/swell/blob/aa000b050bd367a53cb503b4279825f1da8001b6/src/swell/suites/3dvar_atmos/eva/observations-geos_atmosphere.yaml#L5

3dFGAT - https://github.com/GEOS-ESM/swell/blob/aa000b050bd367a53cb503b4279825f1da8001b6/src/swell/suites/3dfgat_atmos/eva/observations-geos_atmosphere.yaml#L5

**Comment by asewnath** [comment]
This will be handled in the new eva increment task we've previously discussed. Task will update the `eva_override` dictionary to account for keywords in the eva config yamls.

 3dfgat-atmos: The `eva_override` dictionary will contain keyword `window_begin` which is defined by `self.da_window_params.window_begin(window_offset)` where `window_offset` is `PT3H`. The `window_begin` keyword will be used to template the input file in a new `eva-increment.yaml` eva config file in the `3dfgat-atmos` suite, which will look something like this: `filename: {{cycle_dir}}/swell-3dfgat_atmos.increment-iter1.{{window_begin}}.nc4`

 3dvar-atmos: The `eva_override` dictionary will contain keyword `cycle_time` which is defined by the current cycle time passed into the task. The `cycle_time` keyword will be used to template a new `eva-increment.yaml` eva config file in the `3dvar-atmos` suite.

**Comment by rtodling** [comment]
Hi Akira, good read what you wrote here ... can I ask you what the status of this is? We are in the process of bringing the 3d stuff to develop ..

**Comment by asewnath** [comment]
Hi @rtodling, I was under the impression that I was going to wait for 3dvar to be merged into develop before creating the eva_increment task. Would you prefer I start working on it now? I can make a branch off of your 3dvar PR branch
