### ISSUE TITLE
Some all sky data used in JEDI/SWELL seems suspicious

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#317]
I am noticing the following: 

The JEDI/SWELL run has the following use of GMI and AMSR2:

20211212 000000 , Jo(AMSR2 GCOM-W1)       *   = 14182.8, nobs = 56413,
20211212 000000 , Jo(GMI GPM)                       *   = 5951.13, nobs = 41772,

GSI (x0048) on the other hand has the following:

20211212 000000 , Jo(AMSR2W1)    =  1.0723E+03, nobs =    7969 ,
20211212 000000 , Jo(GMI-GPM)    =  2.6653E+03, nobs =   18365 ,

is this associated w/ the errors in GSI that MJK has been fixing (has fixed); and the fact that perhaps JEDI doesn't have such errors?

**Comment by gmao-jjin3** [comment]
@rtodling It looks that observations in all active and passive channels are counted.  There are 14 channels in AMSR2 data, and two of them are assimilated in GSI.   56413 is about 7969 * 14/2.

**Comment by rtodling** [comment]
> @rtodling It looks that observations in all active and passive channels are counted. There are 14 channels in AMSR2 data, and two of them are assimilated in GSI. 56413 is about 7969 * 14/2.

if the obs are "counted" as you say ... it means they are assimilated ... which means there is an issue in the yaml file, isn't it?

There is definitely something missing for AMSR2 ... the yaml has no use_flag reference ... the database filler cannot properly assign which channels are used vs which are not - compare w/ e.g., amsua_n19.yaml

BTW: the same is exactly so for GMI.

**Comment by gmao-jjin3** [comment]
@rtodling Agree.  "use_flag checks" need to be added in these configurations.
