### ISSUE TITLE
Convert ncdiag to IODA is now broken

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#334]
Not clear whether the changes the obs group has been talking about associated w/ the format of the sat bias files has come into JEDI-dev ... but that is now braking in swell and the converters.

**Comment by Dooruk** [comment]
Can you share the error message please?

**Comment by rtodling** [comment]
Is there an auto test for the converters? I mean is the ncdiag converter in the tier 1 set of tests?

**Comment by Dooruk** [comment]
Tier 2 tests does run convert ncdiag. So it should fail tonight and I would be able to see the error message then.

Can you see [this](https://github.com/GEOS-ESM/CI-workflows/issues/9) regarding CI-workflows please, I could use your input.

**Comment by rtodling** [comment]
> Tier 2 tests does run convert ncdiag. So it should fail tonight and I would be able to see the error message then.
> 
> Can you see [this](https://github.com/GEOS-ESM/CI-workflows/issues/9) regarding CI-workflows please, I could use your input.

ok, if so, then it should have failed last night, no?

**Comment by rtodling** [comment]
This is the error:

   Diag.toGeovals(self.cycle_dir())
  File "/discover/nobackup/rtodling/SwellExperiments/swell-convert_ncdiags/jedi_bundle/build/lib/python3.10/pyiodaconv/gsi_ncdiag.py", line 805, in toGeovals
    "nlevs", self.df.dimensions["atmosphere_pressure_coordinate_arr_dim"].size)
KeyError: 'atmosphere_pressure_coordinate_arr_dim'
2024-05-06T21:18:43Z CRITICAL - failed/ERR

The code is looking for a variable that does not exist - perhaps JEDI/EMC added a variable we don't have in the NCdiag files! Although that's a very general field!

**Comment by gmao-jjin3** [comment]
Don't see that failure in creating Geovals in my swell-ufo test after updating my JEDI.

**Comment by Dooruk** [comment]
@rtodling Tier2 tests are running `convert-ncdiags` successfully, I can point you to the folder. Are you sure you didn't change anything locally?

**Comment by Dooruk** [comment]
Closing this as the issue was not reproducible by other users.
