### ISSUE TITLE
Produce SOCA increment plots using EVA

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#342]
Essentially having SOCA increment plots since `eva_increments` task is already created, by @asewnath 😄. The only difference with the `geos_atmosphere` would be the `SOCArestart` data reader in EVA looks for a static file (`soca_gridspec.nc`) and that is located in the `cycle_dir` under `soca/`

We could have the surface slices for `Temp` and `Salt` which are 3D. `ave_ssh` is in 2D so that wouldn't need slicing.

**Comment by asewnath** [comment]
Hey @Dooruk, I've added an example eva increment config yaml to 3dvar and modified the eva_increment task to handle the soca case. You can try out the changes/modify the eva increment config file in the `feature/soca_inc` branch

**Comment by Dooruk** [comment]
Thank you @asewnath, this is quite helpful.
