### ISSUE TITLE
Adding ensemble mean

### ISSUE THREAD

**Issue by metdyn** [GEOS-ESM/swell#365]
From a discussion with @rtodling, I will be testing and adding an ensemble mean to the workflow.

**Comment by rtodling** [comment]
Sounds good Yonggang ... pls keep feeding to this if you find difficulties.

**Comment by rtodling** [comment]
@metdyn you pinged me on Teams saying this: 

`I am creating a separate suites/ensemblemean/flow.cylc as a mimic to suites/localensembleda, and I am going to make it run.  It seems straight forward.`

I replied discouraging you for adding a flow just for this. This is what I said:

`why do you need a separate flow.cylc?  I mean you can do that but the fact is that the ensemble mean is going to be called within the localensembleda flow - so I'd rather you put it there - you can have a knob in that flow that says, ensmeanonly = true and that way the rest of the localensemble would not be called ...`

I just wanted to put the exchange here in case we don't see the Teams reply before you start working on it.

**Comment by Dooruk** [comment]
Closed by #397
