### ISSUE TITLE
case_switching.py seems to lead to an unexpected result

### ISSUE THREAD

**Issue by metdyn** [GEOS-ESM/swell#385]
I realized the `case_switching.py` seems to have some unexpected effect:
- I added `class GetEnsembleMeanVariance(taskBase):` in get_ensemble_meanvariance.py
  The class name is changed to  `GetEnsembleMeanvariance` (camel change Variance to variance), such that I got an output error:

```
GetEnsMeanVariance-geos_atmosphere/01/job.err:Error: Invalid value for '{BuildGeos|BuildGeosByLinking|BuildJedi|BuildJediByLinking|CleanCycle|CloneGeos|CloneGeosMksi|CloneJedi|EvaIncrement|EvaJediLog|EvaObservations|GenerateBClimatology|GenerateBClimatologyByLinking|GenerateObservingSystemRecords|GetBackground|GetBackgroundGeosExperiment|GetEnsemble|GetEnsembleMeanvariance|GetGeosAdasBackground|GetGeosRestart|GetGeovals|GetGsiBc|GetGsiNcdiag|GetObservations|GsiBcToIoda|GsiNcdiagToIoda|LinkGeosOutput|MoveDaRestart|MoveForecastRestart|PrepGeosRunDir|PrepareAnalysis|RemoveForecastDir|RunGeosExecutable|RunJediHofxEnsembleExecutable|RunJediHofxExecutable|RunJediLocalEnsembleDaExecutable|RunJediUfoTestsExecutable|RunJediVariationalExecutable|SaveObsDiags|SaveRestart|StageJedi|StoreBackground}': '


**GetEnsembleMeanVariance**' is not one of 'BuildGeos', 'BuildGeosByLinking', 'BuildJedi', 'BuildJediByLinking', 'CleanCycle', 'CloneGeos', 'CloneGeosMksi', 'CloneJedi', 'EvaIncrement', 'EvaJediLog', 'EvaObservations', 'GenerateBClimatology', 'GenerateBClimatologyByLinking', 'GenerateObservingSystemRecords', 'GetBackground', 'GetBackgroundGeosExperiment', 'GetEnsemble', 

'**GetEnsembleMeanvariance**', 
'GetGeosAdasBackground', 'GetGeosRestart', 'GetGeovals', 'GetGsiBc', 'GetGsiNcdiag', 'GetObservations', 'GsiBcToIoda', 'GsiNcdiagToIoda', 'LinkGeosOutput', 'MoveDaRestart', 'MoveForecastRestart', 'PrepGeosRunDir', 'PrepareAnalysis', 'RemoveForecastDir', 'RunGeosExecutable', 'RunJediHofxEnsembleExecutable', 'RunJediHofxExecutable', 'RunJediLocalEnsembleDaExecutable', 'RunJediUfoTestsExecutable', 'RunJediVariationalExecutable', 'SaveObsDiags', 'SaveRestart', 'StageJedi', 'StoreBackground'.
```

**Comment by Dooruk** [comment]
There seems to be a discrepancy between the class name `GetEnsembleMeanVariance` and the job name `GetEnsMeanVariance` you submitted, they should be the same.

**Comment by metdyn** [comment]
@Dooruk,
I am not through the problem yet. 
The task class name needs to be spelled out exactly in the flow.yaml template,  but a classname `A` and job name `X` are uncorrelated in cylc.  E.g.,
```
  GetBackground-geos_atmosphere => X => RunJediHofxEnsembleExecutable-geos_atmosphere_pack0
    [[X]]
        script = "swell task GetEnsembleMeanvariance $config -d $datetime -m geos_atmosphere"
```
gives as expected
```
└── X
    ├── 01
    │   ├── job
    │   ├── job-activity.log
    │   ├── job.err
    │   ├── job.out
    │   └── job.status
    └── NN -> 01
```

There is an upper lower case conversion .py file in swell that shows hard coded 
`utilities/scripts/utility_driver.py:            util_scripts.append(snake_case_to_camel_case(base_name[0:-3]))`, though I did not test at all. 

If we want to reproduce, we can add
task/AaBbCcDdEe.py
job1 ==> X ==> job2
    [[X]]
        script = "swell task AaBbCcDdEe $config -d $datetime -m geos_atmosphere"

It's an unimportant side walk and a hidden bug.

**Comment by asewnath** [comment]
Hi Yonggang, if you are still having this issue, try adding an underscore before `variance` in the file name itself. Change `get_ensemble_meanvariance.py` to `get_ensemble_mean_variance.py`

**Comment by metdyn** [comment]
Thank you, @asewnath, that helps.  I am now avoiding camels in those long names.
