### ISSUE TITLE
Add `--no-requeue` flag to SLURM submissions

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#388]
Received a yellow card from NCCS:

> "RunJediVariationalExecutable" job on Discover today has been running compute nodes out of memory, causing them to crash. The job re-queues and re-runs on new nodes after each failure, with the same result each time - this can be prevented with the Slurm job option: #SBATCH --no-requeue).

This happened to me while running `3dvar_cycle` on SLES15. While NCCS is figuring out what went wrong, we just need to add the flag hard-coded while submitting SLURM jobs.

..maybe a memory leak?

**Comment by Dooruk** [comment]
@ashiklom, I tried to add this SLURM directive key using the `slurm.yaml` under `platform`. I added `no-requeue: ''` which worked but this is how it looks like:


<img width="474" alt="Screenshot 2024-07-17 at 5 29 08 PM" src="https://github.com/user-attachments/assets/8d09e143-1c73-4184-96b4-65c7bb0cc11d">

Do you think there is a better way to tackle this other than having an if statement if the value doesn't exist here in the `flow.cylc` file:

```jinja2
        [[[directives]]]
        {%- for key, value in scheduling["EvaObservations"]["directives"][model_component].items() %}
            --{{key}} = {{value}}
        {%- endfor %}
```

**Comment by ashiklom** [comment]
Good catch! I hadn't planned on slurm options that don't expect parameters.

Unfortunately, I don't think there's any way to get around this without changing all the Jinja2 templates.

The easiest thing is probably to add `if-else` clauses to all these Jinja2 templates checking for `None`. I.e.,

```python
import jinja2

template = jinja2.Template(
    """
The value of variable 1 is {{ var1 }}.
The value of variable 2 is {% if var2 -%} {{ var2 }} {%- else -%} not set {%- endif -%}.
    """
)

print(template.render({
    "var1": "value1",
    "var2": "value2"
}))

# The value of variable 1 is value1.
# The value of variable 2 is value2.

print(template.render({
    "var1": "value1",
    "var2": None
}))

# The value of variable 1 is value1.
# The value of variable 2 is not set.
```

This should work with `var2` being either `None` or the empty string `''`, because both are "false-y".

I can patch this quickly and open a PR.

**Comment by Dooruk** [comment]
Just for documenting purposes, Cylc still requires `=` sign while handling [options with no argument](https://cylc.github.io/cylc-doc/stable/html/user-guide/task-implementation/job-submission.html#directives-section-quirks-pbs-sge).

**Comment by Dooruk** [comment]
Is `--no-requeue` `#SBATCH` option not compatible with `dastest` and/or `preops`? I can run SWELL suites with my account `advda` bit CI tests fail with this setup on `gmao_ci` account:

<img width="261" alt="Screenshot 2024-07-19 at 1 17 11 PM" src="https://github.com/user-attachments/assets/0019f63c-007b-442d-91b6-23c4b190ae25">

`2024-07-19T16:54:14Z [STDERR] sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified`

I received this error for this Tier1 workflow:

https://github.com/GEOS-ESM/swell/actions/runs/10011537916

@mathomp4 @jardizzo

**Comment by mathomp4** [comment]
Hmm. I mean, I can't see why that flag would care! You might need to ping NCCS

**Comment by Dooruk** [comment]
Ok, I just realized it was the account entry in the global YAML file, silly mistake by me.
