### ISSUE TITLE
Bug in `build_jedi` workflow

### ISSUE THREAD

**Issue by asewnath** [GEOS-ESM/swell#392]
When running `create` for jedi_build_method instead of default `use_existing`, `BuildJedi` task is called and it fails with these errors:

```
Linking CXX executable cmTC_5dd32
/gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-1.7.0/envs/ue-intel-2021.6.0/install/intel/2021.6.0/cmake-3.23.1-cjmwmqd/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5dd32.dir/link.txt --verbose=1
/usr/local/intel/oneapi/2021/compiler/2022.1.0/linux/bin/intel64/icpc -L/usr/local/other/gcc/11.2.0/lib64    -Wl,--disable-new-dtags  CMakeFiles/cmTC_5dd32.dir/src.cxx.o -o cmTC_5dd32  -ldl -lbacktrace
ld: cannot find -lbacktrace: No such file or directory
CMakeFiles/cmTC_5dd32.dir/build.make:99: recipe for target 'cmTC_5dd32' failed
gmake[1]: *** [cmTC_5dd32] Error 1
gmake[1]: Leaving directory '/gpfsm/dnb34/asewnath/SwellExperiments/swell-hofx/jedi_bundle/build/CMakeFiles/CMakeTmp'
Makefile:127: recipe for target 'cmTC_5dd32/fast' failed
gmake: *** [cmTC_5dd32/fast] Error 2
```

**Comment by Dooruk** [comment]
At what stage is this error occurring?

**Comment by asewnath** [comment]
It's failing at the `BuildJedi` task. It runs through some of the cmake. Looks like it cleared through `oops`, `gsibec`, and looks like error is during `saber` build since `saber` build is incomplete. Output from log:

```
Found CMake version 3.23.1
CMake Error at saber/CMakeLists.txt:53 (find_package):
  By not providing "Findvader.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "vader", but
  CMake did not find one.

  Could not find a package configuration file provided by "vader" (requested
  version 1.7.0) with any of the following names:

    vaderConfig.cmake
    vader-config.cmake

  Add the installation prefix of "vader" to CMAKE_PREFIX_PATH or set
  "vader_DIR" to a directory containing one of the above files.  If "vader"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by Dooruk** [comment]
Ok, there are two things happening here:

1) (easy) build order should change, now `saber` depends on `vader` https://github.com/orgs/JCSDA-internal/discussions/143
2) There is also an FMS update that requires module changes

I am working on 2, having issues with `fv3-jedi` build, i will include 1 in this PR as well:

https://github.com/GEOS-ESM/jedi_bundle/pull/41

**Comment by Dooruk** [comment]
I triggered this with Tier 2 and received a new type of error:

`/discover/nobackup/gmao_ci/swell/tier2/10221631690/build_jedi_FAILED/swell-build_jedi-10221631690/cylc-run/swell-build_jedi-10221631690-suite/run1/log/job/1/CloneJedi/01/job.err`

https://github.com/GEOS-ESM/swell/actions/runs/10221631690

Weird that it would fail at `CloneJedi`.

**Comment by asewnath** [comment]
Just to clarify, the original bug was in the `BuildJedi` task, not necessarily in the `build_jedi` workflow. That original bug is fixed with the new `jedi_bundle` changes. But more than happy for this issue to become about the `build_jedi` workflow 😄

**Comment by Dooruk** [comment]
> Just to clarify, the original bug was in the `BuildJedi` task, not necessarily in the `build_jedi` workflow. That original bug is fixed with the new `jedi_bundle` changes. But more than happy for this issue to become about the `build_jedi` workflow 😄

Good clarification, I just switched the title!

**Comment by Dooruk** [comment]
Ok, figured it out, it's a minor issue, will make a PR momentarily.
