### ISSUE TITLE
(SE) Temporary folder handling

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#432]
There are certain `codetests` that create templated YAMLs  in `/tmp`, see below:

https://github.com/GEOS-ESM/swell/blob/dae29b4b5f67e0dd344af8a2ad70de67b56ef8cc/src/swell/utilities/scripts/task_question_dicts.py#L144

This location is not reliably erased and NCCS doesn't want us to fill this up so we should have a better temporary file handling.

For codestests;
if everything works fine, they can be deleted.
in case of an error, they should be kept until the user no longer needs them, which could be when the terminal is closed?

**Comment by Dooruk** [comment]
Also somewhat relevant discussion in the GEOSgcm context:

https://github.com/GEOS-ESM/GEOSgcm/issues/814

**Comment by mathomp4** [comment]
If nothing else, that code fragment should probably use the `tempfile` module which is the more Pythonic way of handling temporary files. 

Of course, even that uses `TMPDIR` so we'd want to make sure `TMPDIR` was not `/tmp`.

**Comment by mranst** [comment]
This was addressed by #436 right? `TMPDIR` should be cleared at job close/exit. I believe that's the only instance of this

**Comment by Dooruk** [comment]
> This was addressed by #436 right? `TMPDIR` should be cleared at job close/exit. I believe that's the only instance of this

Yup closed by #436
