### ISSUE TITLE
Adding Bufr2IODA to SWELL

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#435]
This lay out the steps require for us  to incorporate the capabilities of having swell convert bufr files to IODA on the fly.

[] GEOSadas: move obsys.rc to sidb in mksi.

There are two options to implement the converters:
1. Offline converter:
  [] create location within SWELL to hold yaml files involved in convert of all relevant files
  [] work on radiance first
3. Online converter:

**Comment by Dooruk** [comment]
There is the following issue already, would you like to add some these steps there?

https://github.com/GEOS-ESM/swell/issues/378
