### ISSUE TITLE
Incorrect setting in use_flag_clddet for hyperspectral IR

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#441]
In GSI we use a decimal-to-binary conversion to represent settings of the cloud-detection QC. At some point somebody copied the flags used in GSI to the 'use_flag_clddet'  yaml entry in JEDI. Unfortunately, the binary interpretation has no correspondent in JEDI ... I believe JEDI uses channels with entries other than 1 or -1 to do something that is  inconsistent w/ what GSI does.

I believe a filter or two need to be added in the yaml (and perhaps in UFO) so that 31 - he flag used to handle O3-sensitive channels can be handed in JEDI as they are being handled in GSI.

**Comment by gmao-wgu** [comment]
Ricardo, that is not true. I have developed  a filter to handle this in JEDi so that "31"can be used to assimilate observations over only ocean and observations from this channel will be involved in the cloud detection.

**Comment by rtodling** [comment]
> Ricardo, that is not true. I have developed a filter to handle this in JEDi so that "31"can be used to assimilate observations over only ocean and observations from this channel will be involved in the cloud detection.

@gmao-wgu Can you point me to that?  I know the cloud detection thing is done here:

ufo/filters/obsfunctions/CloudDetectMinResidualIR.cc

but I don't see a handling for 31 or decimal to binary ...

**Comment by rtodling** [comment]
> > Ricardo, that is not true. I have developed a filter to handle this in JEDi so that "31"can be used to assimilate observations over only ocean and observations from this channel will be involved in the cloud detection.
> 
> @gmao-wgu Can you point me to that? I know the cloud detection thing is done here:
> 
> ufo/filters/obsfunctions/CloudDetectMinResidualIR.cc
> 
> but I don't see a handling for 31 or decimal to binary ...

I see it here:   ufo/filters/obsfunctions/SurfTypeCheckRad.cc   ....

**Comment by gmao-wgu** [comment]
That is it.
