### ISSUE TITLE
Linear obs operator for MW needs to be given all surface types 

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#462]
This has been found while looking at the SSMI/S issue #460 - the Tskin increment due to SSMI is (obviously) insignificant small in GSI ... and it should be such in JEDI, but in the latter the increment is way too small - and indeed not quite as it should look.

here is a fig:

<img width="603" alt="tskin-ssmis-gs-Xjedi" src="https://github.com/user-attachments/assets/fee701ef-61ea-4731-82f2-0c720eda6fd5">

notice the increments have been blown up by a huge factor (1e5) just so something shows up.

This is what happens when all surfaces are passed to the linear observer --- this is a fix that came in when the T-skin analysis was added to JEDI/GSIBEC - these changes should have been made in when the T-skin was added to  SWELL, but they fell thru the cracks.

This is what happens w/ the fix:

<img width="603" alt="tskin-ssmis-gsiXjedi-fix" src="https://github.com/user-attachments/assets/a80db0f2-02c0-428d-bb89-e2c6bd7bd45f">

The T-skin increments in JEDI are smaller that those from GSI - but the change makes the two results consistent.

**Comment by rtodling** [comment]
The fig below provides illustration of this for ATMS-N20.

NOTICE that inflation value of fields is now only a factor of 10 (as opposed to 1e5 for SSMI/S); way more working channels in ATMS-N20.

 
<img width="603" alt="tskin-atmsn20-gsiXjedi" src="https://github.com/user-attachments/assets/6bdde04f-b034-4d0f-a182-229720573c66">


Since only Water_Temperature is presently in the linear obs operator ... JEDI only produces increments over the ocean.

Within this changed and made consistent - that is, added the other surface types we get:

<img width="603" alt="tskin-ssmis-gsiXjedi-fix" src="https://github.com/user-attachments/assets/897d2b9c-08b8-45c5-a86b-360af5001361">

As w/ SSMI/S the JEDI Tskin increments tend to be smaller - esp. over the ocean ... something to look into at some point.

**Comment by gmao-yzhu** [comment]
It looks correct to add other surfaces to linear operator for SSMI/S, AMSUA, ATMS. I guess this will not be added to AMSR-2 as We don't expect increments over non-water for AMSR-2 and GMI.

**Comment by rtodling** [comment]
I forgot I had already opened an issue on this: issue #424 - would be nice to 

> It looks correct to add other surfaces to linear operator for SSMI/S, AMSUA, ATMS. I guess this will not be added to AMSR-2 as We don't expect increments over non-water for AMSR-2 and GMI.

@gmao-yzhu all of the all-sky have already been address on this issue - the only pending one were the clear-sky MW, which I addressed already in the PR #463

**Comment by rtodling** [comment]
I am closing #424 for the benefit of reducing redundancy.
