### ISSUE TITLE
BlackList for GPSRO implementation seems suspicious

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/swell#480]
I have been using the BlackList filter in the gps.yaml to keep only 269 (SPIRE) data in my test ... that seems to work. Now when I use the same blacklist mechanism to keep only COSMIC E2 (751) it doesn't work ... I seem get way more than I want!

Actually, I am finding that the problem seems to be in GSI ... when all COSMIC-2 is used, 751 shows about 40K observations roughly; when only 751 is used, GSI seems to only get about 13K which is really odd ... JEDI on the other hand comes up w/ about 40K when only 751 is used ... boy what a mind twister!

The question is: is there some QC in GSI that reduces the amount of C2 data if only one satellite is present in the constellation? I am looking for some restriction as such but cannot find it!

**Comment by nprive** [comment]
I don’t use github and don’t know what this means.

-Nikki

From: rtodling ***@***.***>
Date: Tuesday, December 10, 2024 at 4:45 PM
To: GEOS-ESM/swell ***@***.***>
Cc: Prive, Nikki C. (GSFC-610.1)[MORGAN STATE UNIV.] ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [GEOS-ESM/swell] BlackList for GPSRO implementation seems suspicious (Issue #480)
CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Assigned #480<https://github.com/GEOS-ESM/swell/issues/480> to @nprive<https://github.com/nprive>.

**Comment by rtodling** [comment]
My bad ... I was using a mistaken settings in GSI ... will close this - sorry to bug.
