### ISSUE TITLE
YAML Configuration | AMSR2

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#62]
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] GCOM-W1

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] GCOM-W1

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] GCOM-W1

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] GCOM-W1

## Agreement with GSI using Swell

- [ ] GCOM-W1

## Current issues:

- Some differences between swell and gsi

**Comment by gmao-jjin3** [comment]
![amsr2_gcome-w1 UFO_Obs_Number O-F_BC_QC ch09 ps](https://user-images.githubusercontent.com/61251050/173916548-fd76952f-e463-4ce2-b1be-0ad04554d735.png)
![amsr2_gcome-w1 UFO_Obs_Number O-F_BC_QC ch11 ps](https://user-images.githubusercontent.com/61251050/173916553-11668865-e60d-43c3-8d73-c575825c02bc.png)

**Comment by gmao-jjin3** [comment]
![amsr2_gcome-w1 UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch09 ps](https://user-images.githubusercontent.com/61251050/173916680-ddb054d0-2609-47a2-a3e8-f9b73e33e834.png)
![amsr2_gcome-w1 UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch11 ps](https://user-images.githubusercontent.com/61251050/173916683-7c01a1ec-2700-49ea-9a0d-e9590b7c9f41.png)

**Comment by gmao-jjin3** [comment]
![gsi_omb_jedi_omb_density_amsr2_gcom-w1_brightnessTemperature_ch9](https://github.com/GEOS-ESM/swell/assets/61251050/b8499af2-dc5d-4ad6-a289-5afd413620c4)
![gsi_omb_jedi_omb_density_amsr2_gcom-w1_brightnessTemperature_ch11](https://github.com/GEOS-ESM/swell/assets/61251050/8c3b5a77-6645-4545-8bb7-7574c1148028)
![corscat_obserr_vs_gsiobserr_Qc_ch9](https://github.com/GEOS-ESM/swell/assets/61251050/b3489819-c7d1-4e37-b35d-614263cc2190)
![corscat_obserr_vs_gsiobserr_Qc_ch11](https://github.com/GEOS-ESM/swell/assets/61251050/3576ace2-9782-49a1-a52e-6bf304df0134)

Results of the x0048 experiment are reproduced by UFO.
