### ISSUE TITLE
YAML Configuration | GNSSRO

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#67]
## Agreement with GSI using GeoVaLs in UFO (Hofx)

- [x] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Done

## Agreement with GSI using Swell

- [ ] Done

## JEDI PRs

- [ ] https://github.com/JCSDA-internal/ioda-converters/pull/1038
- [x] https://github.com/JCSDA-internal/ioda-converters/pull/1089
- [ ] https://github.com/JCSDA-internal/ufo/pull/2872

## Current issues:

- None

**Comment by danholdaway** [comment]
@gmao-yzhu I've updated the scripts in /discover/nobackup/drholdaw/JediUfoTests so you can make the plots of JEDI h(x) vs GSI h(x) with eva. Interesting the tolerance in the test YAML is set to 1.0e-5 and the test passes. But when I look at the plots (below) there is clearly discrepancy between the systems. Perhaps this is because of there being records and things not being plotted properly.

![gps_bend_gsihofxbc_vs_hofx_bending_angle](https://user-images.githubusercontent.com/27729500/190169251-cb5e4026-2800-43be-8c43-46a678193a01.png)

**Comment by gmao-yzhu** [comment]
I'd like to summarize the issues we have encountered when generating geoval and obs testing files: 
1) added a bunch of variables to the two files; 
2) the two testing files should be sorted based on record-number before they are passed into observation operator; Dan added a sorting script.
3) Jianjun fixed two bugs when writing out geopotential_height_level and air_pressure from GSI.   

**Before fixes:**
![corscat_hofx_vs_gsihofx_old](https://user-images.githubusercontent.com/73974278/202337913-17a6c7a1-622a-4a4f-a3f5-0c71f1cd345a.png)
**After fixes:** 
![corscat_hofx_vs_gsihofx](https://user-images.githubusercontent.com/73974278/202337932-0ec76931-0800-4809-80a6-66245186a481.png)


**Furthermore**, Jianjun incorporated the sorting code in the gsidiag2ioda converter and re-generated the two testing files. The statistics of UFO hofx are the same as those when sorting was done separately, and the scatter plot of generated UFO hofx vs. GSIHofx also looks good:
![corscat_hofx_vs_gsihofx](https://user-images.githubusercontent.com/73974278/202765711-8c05560e-a2ec-45a1-aa3f-f76cf31aa39f.png)

**Be aware,** unlike JCSDA/NCAR, we use air_pressure for the calculation of bending angle in GEOS

**Comment by danholdaway** [comment]
Great to see this looking correct now. Thanks @gmao-jjin3 for all the fixes to GSI.

**Comment by gmao-yzhu** [comment]
Additionally,  I also noticed something such as the following: 
in hofx we have: 
      0.009613695, 0.01315347, 0.01365638, 0.01392684, 0.01417452,
      0.01433338, 0.01489915, _, _, _, _, _, _, _, _, _, _, _, _, _,
      0.01267338, 0.009376252, 0.0122634, 0.01165444, 0.0098651, 0.01006728,
corresponding GsiHofx are:
     0.009613694, 0.01315347, 0.01365638, 0.01392683, 0.01417452, 
     0.01433339, 0.01489916, 0.02764843, 0.02521539, 0.02283077,
      0.02161119, 0.02218309, 0.02430156, 0.02729449, 0.02901491, 0.02864795,
      0.0269617, 0.02625736, 0.02646988, 0.02227982, 
      0.01267338, 0.009376252, 0.01226341, 0.01165444, 0.009865098, 0.01006728

I need to check what is going on.

**Comment by gmao-yzhu** [comment]
I examined the UFO and GSI codes, commented out some lines and added several printout, and found out that the missing values from JEDI were at SR locations, and the hofx values if calculated would be different from GSI values at these locations. Since these hofx at SR locations will be removed by QC eventually, I move forward to next step -- testing quality control steps.

**Comment by gmao-yzhu** [comment]
In GSI, adjusted observation errors are assigned first, final observation errors are obtained by applying quality control mark to removed bad data and reset these bad observations' errors to be zero.  
Here is the original adjusted observation errors: 
![corscat_eferr_vs_adjuster](https://user-images.githubusercontent.com/73974278/213243341-c204bbf4-bdbd-42b9-bbab-35ac391ab0e9.png)

Fixes are made in ufo_roobserror_mod.F90 and gnssro_mod_obserror.F90. 
In gnssro_mod_obserror.F90, the differences with the original code are:
```
91d90
< !real(kind_quad), dimension(nobs) ::  obsErr1
109d107
< !          obsErr1(i)=0.19032 +0.287535 *H_km-0.00260813*H_km**2
113d109
< !          obsErr1(i)=-3.20978 +1.26964 *H_km-0.0622538 *H_km**2
124,125c119
<    else 
<       if ((ObsSaid(i) > 749) .and. (ObsSaid(i) < 756)) then
---
>     else if ((ObsSaid(i) > 749) .and. (ObsSaid(i) < 756)) then
144,158c138,151
<       else 
<         if( abs(obsLat(i)) > 40.0 ) then
<           if ( H_km > 12.00 ) then
<              obsErr(i)=-0.685627 +0.377174 *H_km-0.00421934 *H_km**2
<           else
<              obsErr(i)=-3.27737 +1.20003 *H_km-0.0558024 *H_km**2
<           endif
<         else
<           if( H_km > 18.0 ) then
<              obsErr(i)=-2.73867 +0.447663 *H_km-0.00475603 *H_km**2
<           else
<              obsErr(i)=-3.45303 +0.908216 *H_km-0.0293331 *H_km**2
<           endif
<         end if
<       endif
---
>    else !!!! CDAAC processing
>      if( abs(obsLat(i)) > 40.0 ) then
>        if ( H_km > 12.00 ) then
>           obsErr(i)=-0.685627 +0.377174 *H_km-0.00421934 *H_km**2
>        else
>           obsErr(i)=-3.27737 +1.20003 *H_km-0.0558024 *H_km**2
>        endif
>      else
>        if( H_km > 18.0 ) then
>           obsErr(i)=-2.73867 +0.447663 *H_km-0.00475603 *H_km**2
>        else
>           obsErr(i)=-3.45303 +0.908216 *H_km-0.0293331 *H_km**2
>        endif
>      endif
160,163c153,154
<    endif 
<    obsErr(i) = 0.001 /abs(exp(obsErr(i)))
<    if (ObsSaid(i)==269) obsErr(i) = spiregpserrinf*obsErr(i)
---
>   endif
>   obsErr(i) = 0.001 /abs(exp(obsErr(i)))
```

in ufo_roobserror_mod.F90, the difference with the original UFO code is:
```
<     call bending_angle_obserr_NBAM(obsLat, obsImpH, obsSaid, nobs, obsErr, QCflags, missing)
---
>     call bending_angle_obserr_NBAM(obsLat, obsImpA, obsSaid, nobs, obsErr, QCflags, missing)

```
After fix: 
![corscat_eferr_vs_adjuster](https://user-images.githubusercontent.com/73974278/213243848-3f5d2468-5e50-4c9c-a91a-120e9f03f6d2.png)

**Comment by gmao-yzhu** [comment]
BackgroundCheckRONBAM.cc, a UFO QC code, needs to be changed.
 
Here are the differences between the changed and the original UFO code: 
```
65d64
<   ioda::ObsDataVector<int> isatid(obsdb_, "occulting_sat_id", "MetaData");
97,101c96
<         if ((isatid[0][jobs] > 749 && isatid[0][jobs] < 756) || (isatid[0][jobs] > 265 && isatid[0][jobs] < 269)) {
<            cutoff1  = (-4.725+0.045*imp+0.005*imp*imp)*1.0/2.0;
<         } else {
<            cutoff1  = (-4.725+0.045*imp+0.005*imp*imp)*2.0/3.0; 
<         }
---
>         cutoff1  = (-4.725+0.045*imp+0.005*imp*imp)*2.0/3.0;
103,115c98,100
<         cutoff3  = 2.0;
<         if (tmp > 240.0) cutoff3  = 0.005*tmp*tmp-2.3*tmp+266.0 ;
<         if ((isatid[0][jobs] > 749 && isatid[0][jobs] < 756) || (isatid[0][jobs] > 265 && isatid[0][jobs] < 269)) {
<            cutoff3=cutoff3*1.0/2.0;
<         } else {
<            cutoff3=cutoff3*2.0/3.0;
<         }
<         if ((isatid[0][jobs] > 749 && isatid[0][jobs] < 756) || (isatid[0][jobs] > 265 && isatid[0][jobs] < 269)) {
<            cutoff4  = (4.0+8.0*cos(lat))*1.0/2.0;
<         } else {
<            cutoff4  = (4.0+8.0*cos(lat))*2.0/3.0;
<         }
< 
---
>         cutoff3  = 4.0/3.0;
>         if (tmp > 240.0) cutoff3  = ( 0.005*tmp*tmp-2.3*tmp+266.0 )*2.0/3.0;
>         cutoff4  = (4.0+8.0*cos(lat))*2.0/3.0;
127,131c112
<         if ((isatid[0][jobs] > 749 && isatid[0][jobs] < 756) || (isatid[0][jobs] > 265 && isatid[0][jobs] < 269)) {
<            cutoff = 0.02*cutoff;
<         } else {
<            cutoff = 0.03*cutoff;
<         }
---
>         cutoff = 0.03*cutoff;
```

So before this QC change, the comparison between the JEDI effective error and GSI final error looks like
![corscat_eferr_vs_finaler_qc](https://user-images.githubusercontent.com/73974278/214696358-cc40a7f5-1abb-4ae4-81ae-d752dcb1098b.png)

after this QC change, the comparison between the JEDI effective error and GSI final error looks like
![corscat_eferr_vs_finaler_qc](https://user-images.githubusercontent.com/73974278/214710350-ff60439b-eeb6-4bf1-8e00-5b6d287ffc78.png)

**Comment by gmao-yzhu** [comment]
Another note: 
When it is considered to be close-to-SR conditions, 
In the original GSI, if obs location is below non-monotonic section, qcfail=.false.  and bending angle will be calculated and used.  However, in the UFO, no hofx is calculated. 

Also, in gross error check, need to add obserr=min(cusemax, max(cusemin, obserr))

**Comment by gmao-jjin3** [comment]
This web site shows the bug fix in GSI which Yanqiu mentioned on Nov 16, 2022. 
https://github.com/GEOS-ESM/GEOSana_GridComp/pull/117/files

**Comment by gmao-jjin3** [comment]
xuanli.li@noaa.gov and  andrew.collard@noaa.gov See above.

**Comment by gmao-jjin3** [comment]
![corscat_hofx_vs_gsihofx](https://github.com/GEOS-ESM/swell/assets/61251050/e2ef6875-b187-4ef0-9d8a-ae166d623b70)
![corscat_eferr_vs_GsiAdjustObsError](https://github.com/GEOS-ESM/swell/assets/61251050/0d5a35e5-2e67-4fc5-8a4c-3882c036c175)

Initial comparisons  of Hofx and assigned observational errors when x0048 data were used on 05/24/2023.

**Comment by gmao-jjin3** [comment]
![corscat_hofx_vs_gsihofx](https://github.com/GEOS-ESM/swell/assets/61251050/a0b27f54-0b6a-45b0-ac76-aab919742061)

![corscat_hofx-gsihofx_vs_gsihofx](https://github.com/GEOS-ESM/swell/assets/61251050/90d8ba74-65fe-41ea-940b-c07ecca2dd7c)


![corscat_eferr_vs_GsiAdjustObsError](https://github.com/GEOS-ESM/swell/assets/61251050/2e32b17d-097c-4248-b2c1-fb41b08dc1ec)
![corscat_qc_norm_vs_ngsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/0611e094-704d-4202-a71f-2656068bbf56)

![Density_qc_norm_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/bebbad1a-7c0e-4d2f-b0e1-2bd173ee62b4)
![Density_qc_norm_gsiomb_vs_omb](https://github.com/GEOS-ESM/swell/assets/61251050/8dec55f7-f267-4324-9633-b383d7d6eef1)
![corscat_eferr_vs_finaler_qc](https://github.com/GEOS-ESM/swell/assets/61251050/0c1e1110-c501-4af6-a4ee-ab91c17516b7)

Now O-F after QC is nearly identical as O-F after QC in GSI after UFO source codes changes.   529566 observations pass QC in UFO; 529557 observations pass QC in GSI. 
Final observational error inflation needs to be added in UFO.

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_GsiAdjustObsError_norm](https://github.com/GEOS-ESM/swell/assets/61251050/dcb690e0-4733-4e14-be3f-1d16e07984d6)
![corscat_hofx-gsihofx_vs_gsihofx_norm](https://github.com/GEOS-ESM/swell/assets/61251050/caed11fa-2c12-4efa-94d8-ed46ccdd0fcc)

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler_qc](https://github.com/GEOS-ESM/swell/assets/61251050/e246d68a-4cf1-402f-815d-135155650894)

First try to inflate observational errors.

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler_qc](https://github.com/GEOS-ESM/swell/assets/61251050/7ca41bc2-5345-4c8c-96b5-094640edaf43)
![corscat_eferr_vs_finaler_diff_JediQC](https://github.com/GEOS-ESM/swell/assets/61251050/e03bac52-707d-4843-b847-4f0e69f2e5ec)
![corscat_eferr_vs_finaler_diff_woqc](https://github.com/GEOS-ESM/swell/assets/61251050/88686af8-76b6-4f10-8fec-767eaaf1abb1)



It is closer......

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler_diff_woqc](https://github.com/GEOS-ESM/swell/assets/61251050/90a2b26a-8d9b-4ee9-a603-290125deda7c)
![corscat_eferr_vs_finaler_diff_JediQC](https://github.com/GEOS-ESM/swell/assets/61251050/0c3622ff-f435-44ed-965a-eb9ba0a97869)

![corscat_hofx-gsihofx_vs_gsihofx_norm](https://github.com/GEOS-ESM/swell/assets/61251050/0cb85723-dc66-46fc-b3db-902fba9e817c)
![Density_qc_norm_gsiomb_vs_omb](https://github.com/GEOS-ESM/swell/assets/61251050/b4843f80-936f-4f99-8f63-172cfa42d4fb)
![Density_qc_norm_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/2f052cb2-dedb-44ba-ad55-66f604b2a8c6)

Okay, those observations passing QC in UFO matches those in GSI after updating a hardwired number in the original UFO code again.  There are no data passing QC in GSI but not in UFO or data passing QC in UFO but not in GSI now.  As a result of perfect match of QC, final observational errors match too, and their differences are within -3e-10 ~ 8e-10!

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler_diff_woqc](https://github.com/GEOS-ESM/swell/assets/61251050/d18c1a98-b9d6-4630-9696-45f83a0270cd)

![corscat_eferr_vs_finaler_diff_JediQC](https://github.com/GEOS-ESM/swell/assets/61251050/5750aa06-8579-4f8e-8b64-64a764555617)
![corscat_hofx-gsihofx_vs_gsihofx](https://github.com/GEOS-ESM/swell/assets/61251050/87018f56-6fff-4e2f-95ef-445b0976296f)

![corscat_hofx-gsihofx_vs_gsihofx_norm](https://github.com/GEOS-ESM/swell/assets/61251050/cd4c85d8-a80f-4bf6-b1b4-f875c38efd42)
![Density_qc_norm_gsiomb_vs_omb](https://github.com/GEOS-ESM/swell/assets/61251050/b30c69bd-ceb0-4a2e-9ea8-8026683e2a5b)

![Density_qc_norm_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/c4c5587e-7d89-43ac-92cd-8b8f5eb7e549)

Okay, those observations passing QC in UFO matches those in GSI after updating a hardwired number in the original UFO code again. There are no data passing QC in GSI but not in UFO or data passing QC in UFO but not in GSI now. As a result of perfect match of QC, final observational errors match too, and their differences are within -3e-10 ~ 8e-10!  UFO Hofx values have the same differences from GSI as before.

**Comment by gmao-jjin3** [comment]
![corscat_eferr_vs_finaler_diff_woqc](https://github.com/GEOS-ESM/swell/assets/61251050/3e8984d3-3ffd-4002-b5d5-a8c7c7283914)
![corscat_eferr_vs_finaler_diff_JediQC](https://github.com/GEOS-ESM/swell/assets/61251050/f164ab57-b9f4-4f36-bd28-b1ee1697f3ad)

![Density_qc_norm_gsiomb_vs_omb](https://github.com/GEOS-ESM/swell/assets/61251050/f9b62d93-48db-4dca-9211-04f60372e716)
![Density_qc_norm_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/57fc6917-39d3-45b8-af9e-cded5419aaca)

![corscat_hofx-gsihofx_vs_gsihofx](https://github.com/GEOS-ESM/swell/assets/61251050/7036f610-a90f-434e-a7db-4f7d14ac7020)

![corscat_hofx-gsihofx_vs_gsihofx_norm](https://github.com/GEOS-ESM/swell/assets/61251050/41aff64c-8aab-4d9f-890e-48a19af1668b)


Okay, those observations passing QC in UFO matches those in GSI after updating a hardwired number in the original UFO code again. There are no data passing QC in GSI but not in UFO or data passing QC in UFO but not in GSI now. As a result of perfect match of QC, final observational errors in UFO match those values in GSI, and their differences are within -3e-10 ~ 8e-10!  UFO Hofx values have the same differences from GSI as before.

**Comment by danholdaway** [comment]
Great @gmao-jjin3!!!

**Comment by danholdaway** [comment]
Was this to do with the levels thing?

**Comment by gmao-jjin3** [comment]
Yeah. The hardwired number in the original UFO code has to be updated correctly.

**Comment by rgelaro** [comment]
This is great news (great work!) Jianjun.  I guess I should have set the date for our dinner a few weeks ago!

**Comment by rgelaro** [comment]
But will the update be just a _different_ hardwired number??

**Comment by gmao-jjin3** [comment]
Don't want to do that. It needs a better way, though it's a minor issue.

**Comment by gmao-yzhu** [comment]
Great!  This hardwired number only affects QC, not Hofx?

**Comment by gmao-jjin3** [comment]
> Great! This hardwired number only affects QC, not Hofx?

No, it doesn't. However, it is a bit puzzling.

**Comment by gmao-jjin3** [comment]
Here is a updated UFO PR:  https://github.com/JCSDA-internal/ufo/pull/2872
Its results match GEOS, x0048 summer run, at 00h 06/15/2022 as shown before. But there is one more data tossed by UFO than by GSI at 00h, 12./12/.2021  in the x0048 winter run:
```

total number of data = 636576
=====================================================
Pass QC in GSI, but not in JEDI
1 ----- lat= 40.77443  lon= 276.47977
1  h= 37458.7  sat= 42  class= 401  gsihofx= 9.508066e-05  jedihofx= 9.508419e-05  gsiQC= 0  JediQC= 19 
  gsi:(o-f)/o= -0.036753464  jedi:(o-f)/o= -0.03679202  
1  gsier0= 6.7459456e-07  jedier0= 6.746067e-07  gsierr= 1.5084393e-06  jedierr= -3.3687953e+38  

number of obs 1
=====================================================
Pass QC in JEDI, but not in GSI
number of obs 0
=====================================================
```

**Comment by gmao-jjin3** [comment]
Here are figures made from the latest develop branch. Hofx values match. There are >700 data which don't match QC.  Note, it is a small percent (0.13%) of the data passing QC in GSI.  However, there are some obviously unmatched final observational errors. 

![corscat_diff_hofx-gsihofx_vs_gsihofx_norm](https://github.com/GEOS-ESM/swell/assets/61251050/9f1b4ab4-9aee-4353-8818-98c208ede8b3)
![Density_qc_omb_vs_gsiomb](https://github.com/GEOS-ESM/swell/assets/61251050/7db4cbc3-f5db-46bf-886b-cffbd1fdb128)
![corscat_eferr_vs_finaler_qc](https://github.com/GEOS-ESM/swell/assets/61251050/fcc5ffcf-fcbc-448a-a638-7351d8c04b2f)

**Comment by danholdaway** [comment]
Thanks @gmao-jjin3 . It's good to see that h(x) still works. Does this mean that the work that's needed (to get large enough error) is only in the filters? All the conflicts before were in the operator right? But if there's a match in h(x) it would suggest the operator is OK.

**Comment by gmao-jjin3** [comment]
@danholdaway Yes, the operator is OK.  The issue sits in error inflation & QC for some sup-refraction data.
