### ISSUE TITLE
YAML Configuration | MHS

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#69]
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] Metop-B
- [x] Metop-C

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] Metop-B
- [x] Metop-C

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Metop-B
- [x] Metop-C

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] Metop-B
- [x] Metop-C

## Agreement with GSI using Swell

- [ ] Metop-B
- [ ] Metop-C

## Current issues:

- None

**Comment by gmao-jjin3** [comment]
A cloud index function for MHS is added in UFO. The observational error inflation function is updated for MHS data in GEOS all-sky assimilation. Now observational errors can be reproduced in UFO.  See the git-hub PR https://github.com/JCSDA-internal/ufo/pull/2072 .

**Comment by gmao-jjin3** [comment]
![mhs_metop-b UFO_Obs_Number O-F_BC_QC ch1 ps](https://user-images.githubusercontent.com/61251050/173491806-aaa0eb09-5636-4475-a68e-7933c98c8cd8.png)
![mhs_metop-b UFO_Obs_Number O-F_BC_QC ch2 ps](https://user-images.githubusercontent.com/61251050/173491807-618dbb9e-cdba-4b1e-b306-8e0a21a28b30.png)
![mhs_metop-b UFO_Obs_Number O-F_BC_QC ch3 ps](https://user-images.githubusercontent.com/61251050/173491809-bfbd92b6-2409-4f30-aca7-a4b8d2ab46c9.png)
![mhs_metop-b UFO_Obs_Number O-F_BC_QC ch4 ps](https://user-images.githubusercontent.com/61251050/173491811-15049c5e-0f42-465b-abaa-2e211205a7b9.png)
![mhs_metop-b UFO_Obs_Number O-F_BC_QC ch5 ps](https://user-images.githubusercontent.com/61251050/173491812-8f1764f5-c16c-4c64-bb2e-655c904f0d8a.png)

**Comment by gmao-jjin3** [comment]
There are still slight differences in number of data passing quality control in GEOS and UFO, even though O-F and obs errors are identical (see below) in the two systems.

**Comment by gmao-jjin3** [comment]
![mhs_metop-b UFO_EffectiveError GsiFinalObsError ch3 ps](https://user-images.githubusercontent.com/61251050/173493689-dfa85123-f453-4c21-b7a1-24553954274c.png)
![mhs_metop-b UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC ch3 ps](https://user-images.githubusercontent.com/61251050/173493713-90083aed-a925-4f19-9cd0-fecb1b5171ad.png)

**Comment by danholdaway** [comment]
Would you be able to provide specifics on the number of observations passing QC? I suppose the values are not identical to all digits so some things might be falling on a different side of an if statement somewhere

**Comment by gmao-jjin3** [comment]
A note:  It is "average_surface_temperature_within_field_of_view@GeoVaLs", not the "surface_temperature_where_sea@GeoVaLs", that is used by GSI to check sea surface temperature.

**Comment by gmao-jjin3** [comment]
![mhs_metop-b UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch5 ps](https://user-images.githubusercontent.com/61251050/175757570-57cf03b3-b9fb-446b-80fb-75d4807d5613.png)
![mhs_metop-b UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch4 ps](https://user-images.githubusercontent.com/61251050/175757574-0f9595d4-ddf7-42c8-a9de-0466940c6c7a.png)
![mhs_metop-b UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch3 ps](https://user-images.githubusercontent.com/61251050/175757575-c8f203f8-622c-4ed6-a12f-aadb70a929c8.png)

**Comment by gmao-jjin3** [comment]
Now, there are identical QC filters in UFO and GEOS for MHS in all-sky conditions after updating ObsErrorBoundMW.cc and other programs in the UFO git-hub PR: https://github.com/JCSDA-internal/ufo/pull/2102

**Comment by danholdaway** [comment]
Great stuff @gmao-jjin3. Can you add the YAML files to swell? Then once your changes are in develop of ufo we can tag again pointing to an updated build of JEDI.

**Comment by gmao-jjin3** [comment]
**mhs_metop-c HofX, bias correction, and quality control are reproduced by UFO.**  
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch5 ps](https://user-images.githubusercontent.com/61251050/176349219-ce8ca1c8-7137-43fe-bccc-b725e55fca2b.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch4 ps](https://user-images.githubusercontent.com/61251050/176349226-8df09bf1-f662-4e73-80a7-ffc4f22bb202.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch3 ps](https://user-images.githubusercontent.com/61251050/176349228-b72fb820-c066-4168-bc39-783985c96b73.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch2 ps](https://user-images.githubusercontent.com/61251050/176349229-e4daf8d1-124b-428d-b520-40d0c6b03e36.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch1 ps](https://user-images.githubusercontent.com/61251050/176349230-9e86b84a-c7f8-4181-96cb-c47c0bc8329e.png)

**Comment by gmao-jjin3** [comment]
![mhs_metop-c UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch5 ps](https://user-images.githubusercontent.com/61251050/176349335-241916c4-6f93-4169-94f9-37c417faabac.png)
![mhs_metop-c UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch4 ps](https://user-images.githubusercontent.com/61251050/176349338-6c76d474-0a29-4c2c-a599-7aa44073d8ac.png)
![mhs_metop-c UFO_Obs_Number ObsValue-GsiHofXBc_BC_QC ch3 ps](https://user-images.githubusercontent.com/61251050/176349339-c4085ef9-2866-4d3f-9478-053d47ea9a30.png)

**Comment by gmao-jjin3** [comment]
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch5 ps](https://user-images.githubusercontent.com/61251050/176349423-1b789d7e-b736-4a97-b3a8-13d4c027c159.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch4 ps](https://user-images.githubusercontent.com/61251050/176349424-0cdcbe71-32c0-4bc7-bc5a-91d6039f71de.png)
![mhs_metop-c UFO_ObsValue-hofx ObsValue-GsiHofXBc_BC_QC ch3 ps](https://user-images.githubusercontent.com/61251050/176349426-8fe614a2-bce1-4a62-817d-ca1a21a2a6aa.png)

**Comment by gmao-jjin3** [comment]
![mhs_metop-c UFO_EffectiveError GsiFinalObsError ch3 ps](https://user-images.githubusercontent.com/61251050/176351963-a5042df8-0ab6-4444-b61c-32c00120caec.png)
