### ISSUE TITLE
YAML Configuration | MLS

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#70]
## Agreement with GSI using UFO

- [x] AURA

## Agreement with GSI using Swell

- [x] AURA

## Current issues:

- Repeat times in the ioda data converted from the raw files. Need to look at the raw files.
- Might need some new code to do error inflation by level.

**Comment by kwargan** [comment]
Getting an error in EvaDriver when running swell 1.0.5 with OMI. No plots get generated. The error log says:
[A lot of things followed by]
File "/discover/nobackup/drholdaw/opt/core/miniconda/3.9/lib/python3.9/site-packages/xarray/backends/netCDF4_.py", line 167, in _nc4_require_group
    raise OSError("group not found: %s" % key, e)
OSError: [Errno group not found: GsiEffectiveQC] 'GsiEffectiveQC'
2022-06-08T17:41:00Z CRITICAL - failed/ERR

**Comment by karpob** [comment]
MLS passes ufo test pretty much down to precision:
nobs= 29736 Min=-9.5467389193970575e-07, Max=1.0826355616444516e-06, RMS=1.7286660774732043e-07

**Comment by karpob** [comment]
MLS looks fine in Swell also:
![image](https://user-images.githubusercontent.com/12737769/185453258-7fee0e13-4775-453f-a4e9-b1a25cde289a.png)
