### ISSUE TITLE
YAML Configuration | RASS

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#72]
## Agreement with GSI using GeoVaLs in UFO (Hofx)

- [ ] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [ ] Done

## Agreement with GSI using Swell

- [ ] Done

## Current issues:

- None

**Comment by gmao-jjin3** [comment]
![corscat_omb_vs_gsiomb](https://user-images.githubusercontent.com/61251050/217627907-ebcc14c6-ec57-4326-8058-3538b75af73a.png)
![corscat_EffectiveQC_vs_GsiEffectiveQC](https://user-images.githubusercontent.com/61251050/217628030-4fa15931-d3c6-4ef2-8104-ce2803f7c1d6.png)
![density_qc_omb_vs_gsiombbc](https://user-images.githubusercontent.com/61251050/217628049-80d07112-f82d-4e69-80a0-d6d2cb4dd864.png)

**Comment by gmao-jjin3** [comment]
Data are not used in GSI or JEDI.
