### ISSUE TITLE
YAML Configuration | Scatwind

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#74]
## Agreement with GSI using GeoVaLs in UFO (Hofx)

- [x] Done

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] Done

## Agreement with GSI using Swell

- [ ] Done

## Current issues:

- None

**Comment by gmao-wgu** [comment]
Agreement with GSI using GeoVaLs in UFO Hofx can be reached for scatwind, which can be proved by the following plot:

![scatwind_density_omb_vs_gsiomb](https://user-images.githubusercontent.com/59488002/207994391-4bfcba72-094c-47ae-95ef-1bb6588205ea.png)

**Comment by danholdaway** [comment]
> Agreement with GSI using GeoVaLs in UFO Hofx can be reached for scatwind, which can be proved by the following plot:
> 
> ![scatwind_density_omb_vs_gsiomb](https://user-images.githubusercontent.com/59488002/207994391-4bfcba72-094c-47ae-95ef-1bb6588205ea.png)

@gmao-wgu this is without QC though right?

**Comment by gmao-wgu** [comment]
@danholdaway yeah, without QC.

**Comment by gmao-wgu** [comment]
The filter of the ambiguity check for ASCAT was implemented and the geometric height check to inflate obs errors if the reported one is outside of the domain was also completed. Here are the final plots:

The number of obs passing QC between the GSI and UFO:
    
![density_qced_omb_vs_gsiomb (3)](https://user-images.githubusercontent.com/59488002/210645440-fba82f0b-ce68-4178-98ad-a2679e8262da.png)

The final obs error comparison between the GSI and UFO:

![corscat_qced_eferr_vs_gsifinal](https://user-images.githubusercontent.com/59488002/210645833-b1d5d8ad-310e-4b0b-a394-c6c0afe2d3f4.png)

The OMF comparison between the GSI and UFO:

   
![corscat_omb_vs_gsiomb](https://user-images.githubusercontent.com/59488002/210646155-bc4808fb-15a2-4a53-b888-75ca3ede448e.png)

Error Inflation comparison: the GSI vs UFO
![corscat_JediErrorInfl_vs_GsiErrorInfl_kx290](https://user-images.githubusercontent.com/59488002/210668814-6392068e-b71d-4620-a903-2a6590ff9739.png)
