### ISSUE TITLE
YAML Configuration | SSMIS

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#79]
## Agreement with GSI using GeoVaLs in UFO (Hofx no bias correction)

- [x] F17

## Agreement with GSI using GeoVaLs in UFO (Bias correction)

- [x] F17

## Agreement with GSI using GeoVaLs in UFO (Quality control)

- [x] F17

## Agreement with GSI using GeoVaLs in UFO (Hofx with bias correction)

- [x] F17

## Agreement with GSI using Swell

- [ ] F17

## Current issues:

- None

**Comment by gmao-wgu** [comment]
The hofx generated by JEDI for SSMIS shows good agreement with the hofx generated by GSI, Additionally, the satellite biases  modeled using UFO also match well with the biases identified by GSI. Here are a few plots demonstrating this agreement between GSI and UFO before QC:

![ssmis_f17 UFO_Obs_Number O-F_woBC ch23 ps](https://user-images.githubusercontent.com/59488002/232607072-6d03db6c-deb7-4473-9981-3da47a3d629e.png)

![ssmis_f17 UFO_Obs_Number O-F_BC ch23_bc ps](https://user-images.githubusercontent.com/59488002/232607168-d996f394-a052-4949-9bdd-71d23d506cb5.png)

**Comment by gmao-wgu** [comment]
However, the bias correction for some of passive channels in JEDI performed differently if compared with GSI, as illustrated in the following plots:

Before the bias correction:
![ssmis_f17 UFO_Obs_Number O-F_woBC ch04 ps](https://user-images.githubusercontent.com/59488002/233489629-9e95cfd1-5c83-4c6f-95d7-a96d0683a217.png)
After the bias correction:
![ssmis_f17 UFO_Obs_Number O-F_BC ch04 ps](https://user-images.githubusercontent.com/59488002/233489841-98dd25a3-388a-46fe-ba30-ed993ff24aa8.png)

**Comment by gmao-jjin3** [comment]
Wei, can you replot it by Eva?

**Comment by gmao-wgu** [comment]
@gmao-jjin3 OK, I was only able to generate scatting plots.

**Comment by gmao-wgu** [comment]
By using Eva, I generated the scatter plots for SSMIS_F17 Channel 4 which is a surface sensitive channels as shown in the following:
Before the bias correction:
![corscat_omb_vs_gsiomb_4](https://user-images.githubusercontent.com/59488002/233495169-583952e2-ed65-4115-ad1f-b29d31d9f33c.png)
After the bias corrections:
![corscat_omb_vs_gsiomb_bc_4](https://user-images.githubusercontent.com/59488002/233495226-8d196ddc-2020-48e7-8abf-00b023a3f740.png)

**Comment by gmao-wgu** [comment]
@gmao-jjin3 I printed out the satellite biases respectively from JEDI and GSI at the first location(lat= -88.07, lon = 19.88) from channel  1 to 7:
       ------------------------- ch  ----  JEDI   -----   GSI
      ObsBiasOperator::ybias ch1   -2.56415    -1.8255  passive
      ObsBiasOperator::ybias ch2   -1.21467    -1.2461  passive
      ObsBiasOperator::ybias ch3    0                 0.0       passive
      ObsBiasOperator::ybias ch4   -2.29094    -0.8695 passive
      ObsBiasOperator::ybias ch5    1.24962      1.2496  active
      ObsBiasOperator::ybias ch6   -0.482849   -0.4828 active
      ObsBiasOperator::ybias ch7   -0.750713   -0.7507 active

you could see the biases are almost identical for all active channels, but quite different for some of passive channels.

**Comment by gmao-wgu** [comment]
Here are the bias predictors and corresponding coefficients that have the contributions to the total bias from JEDI for channel 4:

Biaspredictor  ch4 index of pred 1 predictor  1 coeff -0.515186
Biaspredictor  ch4 index of pred 3 predictor  21.0074 coeff 0.002098    0.0440735252
Biaspredictor  ch4 index of pred 4 predictor  -4.58339 coeff -0.021816   0.09999123624
Biaspredictor  ch4 index of pred 5 predictor  -0.0336785 coeff -0.219289  0.0073853245865
Biaspredictor  ch4 index of pred 6 predictor  -0.999433 coeff 0.123816   -0.123745796328  
Biaspredictor  ch4 index of pred 7 predictor  6.65546 coeff -0.228496    -1.52074598816 
Biaspredictor  ch4 index of pred 8 predictor  0.97951 coeff 0.962379    0.94265985429
Biaspredictor  ch4 index of pred 9 predictor  0.984593 coeff -1.63749   -1.61226119157
Biaspredictor  ch4 index of pred 10 predictor  0.989702 coeff -1.03053  -1.01991760206
Biaspredictor  ch4 index of pred 11 predictor  0.994838 coeff 1.41411  1.40681036418

if adding the last 4 terms together gives -0.28270857516 which matches the angle bias from GSI.
The only term does not match with GSI is the surface emissivity sensitivity term with JEDI:-1.52075 while GSI: -0.0993.

**Comment by gmao-wgu** [comment]
The following are the predictors' coefficients from satbias input file for channel 4:

1  -0.515186
2  0
3  -0.089261
4  0.002098
5  -0.021816
6  -0.219289
7  0.123816
8  -0.228496
9  0.962379
10 -1.637489
11 -1.030534
12  1.414107
So it seemed that UFO is missing the predictor of cloud liquid water for channel 4.

**Comment by gmao-jjin3** [comment]
@gmao-wgu  That observation is located in the Antarctic (lat= -88.07, lon = 19.88), therefore, the clw BC term is zero in GSI.  I have been reading through the GSI program, but cannot found an different treatment for passive channels from active channels.

**Comment by gmao-wgu** [comment]
Some passive channels have different bias correction behavior from GSI is due to their sensitivity to surface, which result in  different values from the surface emissivity sensitivity term. This variation arises from the use of different CRTM versions in UFO  and GSI x0044 experiment. Specifically, CRTM 2.3.0 was used in x0044 while JEDI uses CRTM 2.4.0,  which produces more accurate modeling of surface emissivity.

**Comment by gmao-wgu** [comment]
Thanks to @gmao-jjin3 , we have new testing files from GSI with CRTM 2.4.0, the identical version used in UFO.  With this new baseline, we can obtain the exact matches in terms of HofX and the satellite biases for all SSMIS_f17 channels. Here is an example from channel 4:

![ssmis_f17 UFO_Obs_Number O-F_BC ch04 ps_gsi_crtm240](https://github.com/GEOS-ESM/swell/assets/59488002/430ee303-98f1-4eeb-9f0a-2575e8a86563)

**Comment by gmao-wgu** [comment]
@CoryMartin-NOAA  I ported your yaml for SSMIS and ran a test, but encountered an issue preventing it from successfully executing. The error message I received is as follows:

     [31mTest "ufo/ObsFilters/testFilters" failed with unhandled exception:        Reason: An exception occurred inside ioda while opening a variable.
        name:   DerivedMetaData/SSMISScatteringIndex9
        source_column:  0
        source_filename:        /gpfsm/dnb31/wgu/jedi_build/fv3-bundle/ioda/src/engines/ioda/src/ioda/Has_Variables.cpp
        source_function:        ioda::Variable ioda::detail::Has_Variables_Base::open(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &) const
        source_line:    108

Could you tell me how to fix this ?  Thanks

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu any suggestions on this?

**Comment by gmao-wgu** [comment]
I guess this issue is caused by this part of YAML:

  Step 7: Scattering check for channels 9-11 using channels 8 and 17
  - filter: Variable Assignment
    assignments:
    - name: DerivedMetaData/SSMISScatteringIndex9
      type: float
      function:
        name: ObsFunction/Arithmetic
        options:
          variables:
          - name: HofX/brightnessTemperature_17
          - name: ObsBiasData/brightnessTemperature_17
          - name: HofX/brightnessTemperature_8
          - name: ObsBiasData/brightnessTemperature_8
          coefs: [-0.485934, 0.485934, 0.473806, -0.473806]
          intercept: 271.252327

**Comment by emilyhcliu** [comment]
It looks like the IODA complains about not finding some of the variables:
```
variables:
- name: HofX/brightnessTemperature_17
- name: ObsBiasData/brightnessTemperature_17
- name: HofX/brightnessTemperature_8
- name: ObsBiasData/brightnessTemperature_8
```

These variables are calculated on the fly, they are not from the IODA input files.
I would suggest checking the YAML for formatting errors (indentation, ...etc).

**Comment by gmao-wgu** [comment]
@emilyhcliu  Thank you.

**Comment by gmao-wgu** [comment]
I pasted my YAML into one of the yaml validator, it is a valid yaml though.

**Comment by gmao-wgu** [comment]
Thanks to @gmao-jjin3, the issue with variable assignment used in the YAML was solved after it was combined with the difference check as in the following:

     -filter: Difference Check
    filter variables:
    - name: brightnessTemperature
      channels: 9
    reference: ObsValue/brightnessTemperature_9
    value:
      name: ObsFunction/Arithmetic
      options:
        variables:
        - name: HofX/brightnessTemperature_17
        - name: ObsBiasData/brightnessTemperature_17
        - name: HofX/brightnessTemperature_8
        - name: ObsBiasData/brightnessTemperature_8
        coefs: [-0.485934, 0.485934, 0.473806, -0.473806]
        intercept: 271.252327
    maxvalue: 2

**Comment by gmao-wgu** [comment]
So now we are able to test the QC part for SSMIS. The following plots show the histogram of OMF for all active channels after QC
![ssmis_f17 UFO_Obs_Number O-F_BC_QC ch05 ps](https://github.com/GEOS-ESM/swell/assets/59488002/3f40b5a1-f5b2-442e-9d25-2c7c24c9246b)
![ssmis_f17 UFO_Obs_Number O-F_BC_QC ch06 ps](https://github.com/GEOS-ESM/swell/assets/59488002/aaebc53a-4706-4c6f-a7f9-febd062591d1)
![ssmis_f17 UFO_Obs_Number O-F_BC_QC ch07 ps](https://github.com/GEOS-ESM/swell/assets/59488002/e1335aab-a921-4eda-a6d5-0fe815b6d9bd)
![ssmis_f17 UFO_Obs_Number O-F_BC_QC ch23 ps](https://github.com/GEOS-ESM/swell/assets/59488002/72909f47-1569-4642-a5e8-69a0664cc300)
![ssmis_f17 UFO_Obs_Number O-F_BC_QC ch24 ps](https://github.com/GEOS-ESM/swell/assets/59488002/1ed75368-8dd9-4452-8a3c-a126144076ab)
It can be observed that the histogram curves match precisely between UFO(red) and GSI(blue) for all active channels.

**Comment by gmao-wgu** [comment]
The final observation errors also match between UFO and GSI, as can be observed from the following plots:

![ssmis_f17 UFO_EffectiveError GsiFinalObsError_QC ch05 ps](https://github.com/GEOS-ESM/swell/assets/59488002/32d02991-c7aa-489e-8037-3ce13ec778c8)
![ssmis_f17 UFO_EffectiveError GsiFinalObsError_QC ch06 ps](https://github.com/GEOS-ESM/swell/assets/59488002/3aa91d55-e5f7-4ae8-bc92-94b1276a2ebb)
![ssmis_f17 UFO_EffectiveError GsiFinalObsError_QC ch07 ps](https://github.com/GEOS-ESM/swell/assets/59488002/b9f900a8-cc58-4c5d-94c6-9978d0d45ca3)
![ssmis_f17 UFO_EffectiveError GsiFinalObsError_QC ch23 ps](https://github.com/GEOS-ESM/swell/assets/59488002/d8d89d89-345f-44c6-a674-4d20d424d814)
![ssmis_f17 UFO_EffectiveError GsiFinalObsError_QC ch24 ps](https://github.com/GEOS-ESM/swell/assets/59488002/4ec8d3c1-4aeb-48ab-8f8f-2f14875d2641)

**Comment by emilyhcliu** [comment]
> Thanks to @gmao-jjin3, the issue with variable assignment used in the YAML was solved after it was combined with the difference check as in the following:
> 
> ```
>  -filter: Difference Check
> filter variables:
> - name: brightnessTemperature
>   channels: 9
> reference: ObsValue/brightnessTemperature_9
> value:
>   name: ObsFunction/Arithmetic
>   options:
>     variables:
>     - name: HofX/brightnessTemperature_17
>     - name: ObsBiasData/brightnessTemperature_17
>     - name: HofX/brightnessTemperature_8
>     - name: ObsBiasData/brightnessTemperature_8
>     coefs: [-0.485934, 0.485934, 0.473806, -0.473806]
>     intercept: 271.252327
> maxvalue: 2
> ```

@gmao-wgu What exactly went wrong in the original one (from EMC)?

**Comment by gmao-wgu** [comment]
@emilyhcliu The variable assignment itself is not the issue, but somehow the newly derived variables can not be used in the difference check.

**Comment by gmao-wgu** [comment]
@emilyhcliu can I ask you a question about the filter of NearSSTRetCheckIR?

       - filter: Bounds Check
    filter variables:
    - name: brightnessTemperature
      channels: *all_channels
    test variables:
    - name: ObsFunction/NearSSTRetCheckIR
      channels: *all_channels
      options:
        channels: *all_channels
        use_flag: &useflag [ -1,  -1, -1, -1,  1,  1,  1, -1, -1, -1,
                    -1,  -1, -1, -1, -1, -1, -1, -1, -1, -1,
                    -1,  -1,  1,  1]
        error parameter vector: [ 1.50, 0.50, 0.50, 0.50, 0.50, 1.00, 1.00, 3.00, 3.00, 3.00,
                                3.00, 2.40, 1.27, 1.44, 3.00, 1.34, 1.74, 3.75, 3.00, 3.00,
                                2.00, 6.40, 1.00, 1.00]
    maxvalue: 1.0e-12
    action:
      name: reject

Why did you include "error parameter vector" in this filter?  It was not an option for NearSSTRetCheckIR.

**Comment by emilyhcliu** [comment]
We have code changes associated with it.
I will issue an PR soon.

**Comment by gmao-wgu** [comment]
@emilyhcliu I appreciate it if  you could provide further details about this PR. Thanks.

**Comment by emilyhcliu** [comment]
The change is related to how and where to get the initial obs error.
We want to avoid getting the initial obs error from the IODA file directly.

**Comment by gmao-wgu** [comment]
@emilyhcliu Thanks, but we already specify the initial errors at the beginning of the obs filters, which will replace the obs errors from the IODA file. Then, NearSSTRetCheckIR will read the real time obs errors on the fly.  Therefore, I still could not figure out why the "error parameter vector" is needed in NearSSTRetCheckIR unless the algorithm itself needs the initial obs errors rather than errors after inflation.

**Comment by emilyhcliu** [comment]
@gmao-wgu gmao-wgu
How do you specific our initial erros for IASI (for example)?
I can not access the machine where I have my code changes.  The machine is having issues.  
I will check why I need to do that after the machine is available again and let you know.

**Comment by gmao-wgu** [comment]
@emilyhcliu that is something I will work on. I guess we can specify the initial errors for IASI by using either the observation error covariance matrix or a combination of the error covariance matrix and an "error parameter vector" if the matrix only includes all the active channels.
