### ISSUE TITLE
Updates to GSI to output the required GeoVaLs for conventional data

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#92]
- Code from EMC in SetupW. 
- Rerun the GSI
- Ready to run GeoVaLs test for satellite winds.
- Need to look at what's needed for other conventional data.
- BK: check the naming convention for pressure to make sure it's consistent with what ioda converters expects.

**Comment by gmao-jjin3** [comment]
Hello, @CoryMartin-NOAA  Can you tell me which files you changed in order to make geoval and observational files for testing aircraft observations in UFO?  Thanks.

**Comment by CoryMartin-NOAA** [comment]
@gmao-jjin3 you will need to change each `setup*.f90` file (e.g. `setupt`, `setupw`) and add all of the necessary fields to the netCDF diagnostic output routines. As I linked in the other issue, this has largely been done in the http://github.com/jcsda-internal/gsi feature/jedi_gdas branch that you can use as an example.

**Comment by gmao-jjin3** [comment]
I see.  Thank you @CoryMartin-NOAA .

**Comment by gmao-jjin3** [comment]
Here is a branch in a PR https://github.com/GEOS-ESM/GEOSana_GridComp/pull/93 to be merged later. These changes are only for radiance and satwinds data, not yet for other types of observations.

**Comment by gmao-jjin3** [comment]
More changes in order to write out x0044 results for IODA converter. No changes for GPS data yet. No merge from the develop branch.
https://github.com/GEOS-ESM/GEOSana_GridComp/pull/93
