### ISSUE TITLE
YAML Configuration | OMPS-NM

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#93]
## Agreement with GSI using UFO
- [x] NPP
## Agreement with GSI using Swell

- [x] NPP

## Current issues:

- None

**Comment by karpob** [comment]
Tests passed after using the correct value for coefficients derived from first principles. 
```
coefficients: [0.0078976797]
```
![image](https://user-images.githubusercontent.com/12737769/185425027-9c631374-bb38-4639-b01e-7d3f4af20e3d.png)
![image](https://user-images.githubusercontent.com/12737769/185425219-f729a85f-50f1-476d-be29-c3b080f6b1e8.png)

**Comment by karpob** [comment]
And the corresponding Swell output:
![image](https://user-images.githubusercontent.com/12737769/185441075-3157d9e4-e8c8-4d0e-84e5-dfeaf76a518f.png)
![image](https://user-images.githubusercontent.com/12737769/185441892-69b67724-a070-4af6-83a7-43c6adc47fe3.png)
